package azure_constant_compute_processors

var (
	INSTANCE_TYPE_COMPUTE_PROCESSOR_MAPPING = map[string][]string{
		"A1 v2":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A2 v2":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A2m v2":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A4 v2":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A4m v2":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A8 v2":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"A8m v2":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B1ls":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B1s":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B1ms":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B2s":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B2ms":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B4ms":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B8ms":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B12ms":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B16ms":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"B20ms":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"D2a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D4a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D8a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D16a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D32a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D48a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D64a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D96a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D2as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D4as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D8as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D16as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D32as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D48as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D64as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D96as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"D2d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D4d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D8d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D16d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D32d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D48d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D64d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D2ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D4ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D8ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D16ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D32ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D48ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D64ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D2 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D4 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D8 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D16 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D32 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D48 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D64 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D2s v4":           CascadeLakeSkylakeBroadwellHaswell(),
		"D4s v4":           CascadeLakeSkylakeBroadwellHaswell(),
		"D8s v4":           CascadeLakeSkylakeBroadwellHaswell(),
		"D16s v4":          CascadeLakeSkylakeBroadwellHaswell(),
		"D32s v4":          CascadeLakeSkylakeBroadwellHaswell(),
		"D48s v4":          CascadeLakeSkylakeBroadwellHaswell(),
		"D64s v4":          CascadeLakeSkylakeBroadwellHaswell(),
		"D2 v3":            CascadeLakeSkylakeBroadwellHaswell(),
		"D4 v3":            CascadeLakeSkylakeBroadwellHaswell(),
		"D8 v3":            CascadeLakeSkylakeBroadwellHaswell(),
		"D16 v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D32 v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D48 v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D64 v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D2s v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D4s v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D8s v3":           CascadeLakeSkylakeBroadwellHaswell(),
		"D16s v3":          CascadeLakeSkylakeBroadwellHaswell(),
		"D32s v3":          CascadeLakeSkylakeBroadwellHaswell(),
		"D48s v3":          CascadeLakeSkylakeBroadwellHaswell(),
		"D64s v3":          CascadeLakeSkylakeBroadwellHaswell(),
		"D1 v2":            CascadeLakeSkylakeBroadwellHaswell(),
		"D2 v2":            CascadeLakeSkylakeBroadwellHaswell(),
		"D3 v2":            CascadeLakeSkylakeBroadwellHaswell(),
		"D4 v2":            CascadeLakeSkylakeBroadwellHaswell(),
		"D5 v2":            CascadeLakeSkylakeBroadwellHaswell(),
		"Ds1 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"Ds2 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"Ds3 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"Ds4 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"DsS5 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"DC2s":             []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"DC4s":             []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"DC1s v2":          []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"DC2s v2":          []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"DC4s v2":          []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"DC8 v2":           []string{COMPUTE_PROCESSOR_TYPES["COFFEE_LAKE"]},
		"F2s v2":           CascadeLakeSkylake(),
		"F4s v2":           CascadeLakeSkylake(),
		"F8s v2":           CascadeLakeSkylake(),
		"F16s v2":          CascadeLakeSkylake(),
		"F32s v2":          CascadeLakeSkylake(),
		"F48s v2":          CascadeLakeSkylake(),
		"F64s v2":          CascadeLakeSkylake(),
		"F72s v2":          CascadeLakeSkylake(),
		"F1":               CascadeLakeSkylakeBroadwellHaswell(),
		"F2":               CascadeLakeSkylakeBroadwellHaswell(),
		"F4":               CascadeLakeSkylakeBroadwellHaswell(),
		"F8":               CascadeLakeSkylakeBroadwellHaswell(),
		"F16":              CascadeLakeSkylakeBroadwellHaswell(),
		"F1s":              CascadeLakeSkylakeBroadwellHaswell(),
		"F2s":              CascadeLakeSkylakeBroadwellHaswell(),
		"F4s":              CascadeLakeSkylakeBroadwellHaswell(),
		"F8s":              CascadeLakeSkylakeBroadwellHaswell(),
		"F16s":             CascadeLakeSkylakeBroadwellHaswell(),
		"E2a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E4a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E8a v4":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E16a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E20a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E32a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E48a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E64a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E96a v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E2as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E4as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E8as v4":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E16as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E20as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E32as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E48as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E64as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E96as v4":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"E2d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E4d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E8d v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E16d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E20d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E32d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E48d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E64d v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E2ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E4ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E8ds v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E16ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E20ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E32ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E48ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E64ds v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E80ids v4":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E2 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E4 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E8 v4":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E16 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E32 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E48 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E64 v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E2s v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E4s v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E8s v4":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E16s v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E20s v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E32s v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E48s v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E64s v4":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E80is v4":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E2 v3":            CascadeLakeSkylakeBroadwell(),
		"E4 v3":            CascadeLakeSkylakeBroadwell(),
		"E8 v3":            CascadeLakeSkylakeBroadwell(),
		"E16 v3":           CascadeLakeSkylakeBroadwell(),
		"E20 v3":           CascadeLakeSkylakeBroadwell(),
		"E32 v3":           CascadeLakeSkylakeBroadwell(),
		"E48 v3":           CascadeLakeSkylakeBroadwell(),
		"E64i v3":          CascadeLakeSkylakeBroadwell(),
		"E64 v3":           CascadeLakeSkylakeBroadwell(),
		"E2s v3":           CascadeLakeSkylakeBroadwell(),
		"E4s v3":           CascadeLakeSkylakeBroadwell(),
		"E8s v3":           CascadeLakeSkylakeBroadwell(),
		"E16s v3":          CascadeLakeSkylakeBroadwell(),
		"E20s v3":          CascadeLakeSkylakeBroadwell(),
		"E32s v3":          CascadeLakeSkylakeBroadwell(),
		"E48s v3":          CascadeLakeSkylakeBroadwell(),
		"E64is v3":         CascadeLakeSkylakeBroadwell(),
		"E64s v3":          CascadeLakeSkylakeBroadwell(),
		"D11 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"D12 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"D13 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"D14 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"D15i v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"D15 v2":           CascadeLakeSkylakeBroadwellHaswell(),
		"Ds11 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"Ds12 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"Ds13 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"Ds14 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"Ds15i v2":         CascadeLakeSkylakeBroadwellHaswell(),
		"Ds15 v2":          CascadeLakeSkylakeBroadwellHaswell(),
		"G1":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"G2":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"G3":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"G4":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"G5":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"Gs1":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs2":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs3":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs4":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs5":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M8ms":             CascadeLakeHaswell(),
		"M16ms":            CascadeLakeHaswell(),
		"M32ts":            CascadeLakeHaswell(),
		"M32ls":            CascadeLakeHaswell(),
		"M32ms":            CascadeLakeHaswell(),
		"M64ls":            CascadeLakeHaswell(),
		"M64s":             CascadeLakeHaswell(),
		"M64":              CascadeLakeHaswell(),
		"M64ms":            CascadeLakeHaswell(),
		"M64m":             CascadeLakeHaswell(),
		"M128s":            CascadeLakeHaswell(),
		"M128":             CascadeLakeHaswell(),
		"M128ms":           CascadeLakeHaswell(),
		"M128m":            CascadeLakeHaswell(),
		"M32dms v2":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M64ds v2":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M64dms v2":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M128ds v2":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M128dms v2":       []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M192ids v2":       []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M192idms v2":      []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M32ms v2":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M64s v2":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M64ms v2":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M128s v2":         []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M128ms v2":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M192is v2":        []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M192ims v2":       []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"M208s v2":         []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"M208ms v2":        []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"M416s v2":         []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"M416ms v2":        []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"DS11-1 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS12-1 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS12-2 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E4-2as v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E4-2ds v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E4-2s v3":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E4-2s v4":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS13-2 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-2as v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-2ds v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-2s v3":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-2s v4":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M8-2ms":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS13-4 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-4as v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-4ds v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-4s v3":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E8-4s v4":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS14-4 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-4as v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-4ds v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-4s v3":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-4s v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M8-4ms":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs4-4":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M16-4ms":          []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"DS14-8 v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-8as v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-8ds v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-8s v3":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E16-8s v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs4-8":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-8as v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-8ds v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-8s v3":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-8s v4":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M16-8ms":          []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs5-8":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M32-8ms":          []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-16as v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-16ds v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-16s v3":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E32-16s v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-16s v3":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"Gs5-16":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-16ds v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-16s v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-16as v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M32-16ms":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M64-16ms":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E96-24as v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-32s v3":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-32ds v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-32s v4":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E64-32as v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M64-32ms":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M128-32ms":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"E96-48as v4":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"M128-64ms":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"L8s v2":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L16s v2":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L32s v2":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L48s v2":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L64s v2":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L80s v2":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"L4s":              []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"L8s":              []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"L16s":             []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"L32s":             []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"NC6":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC12":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24r":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC6 Promo":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC12 Promo":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24 Promo":       []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24r Promo":      []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC6s v2":          []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC12s v2":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24rs v2":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24s v2":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC6s v3":          []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC12s v3":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24rs v3":        []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC24s v3":         []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NC4as T4 v3":      []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"NC8as T4 v3":      []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"NC16as T4 v3":     []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"NC64as T4 v3":     []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"NP10s":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NP20s":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NP40s":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NV6":              []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NV12":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NV24":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"NV12s v3":         []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"NV24s v3":         []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"NV48s v3":         []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"ND6s":             []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"ND12s":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"ND24rs":           []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"ND24s":            []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"ND40rs v2":        []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"ND96asr A100 v4":  []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"ND96amsr A100 v4": []string{COMPUTE_PROCESSOR_TYPES["UNKNOWN"]},
		"H8":               []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H8m":              []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16r":             []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16":              []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16mr":            []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16m":             []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H8 Promo":         []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H8m Promo":        []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16 Promo":        []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16r Promo":       []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16m Promo":       []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"H16mr Promo":      []string{COMPUTE_PROCESSOR_TYPES["HASWELL"]},
		"HB60rs":           []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_1ST_GEN"]},
		"HB120rs v2":       []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]},
		"HB120rs v3":       []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"HB120-16rs v3":    []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"HB120-32rs v3":    []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"HB120-64rs v3":    []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"HB120-96rs v3":    []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"HC44rs":           []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"]},
		"S96":              []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S192":             []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S192m":            []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S192xm":           []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S384":             []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S384m":            []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S384xm":           []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S384xxm":          []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S576m":            []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"]},
		"S224":             []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S224oo":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S224m":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S224om":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S224ooo":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S224oom":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448":             []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448oo":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448m":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448om":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448ooo":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S448oom":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672":             []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672oo":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672m":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672om":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672ooo":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S672oom":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896":             []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896oo":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896m":            []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896om":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896ooo":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"S896oom":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"D2as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D4as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D8as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D16as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D32as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D48as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D64as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D96as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D2ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D4ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D8ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D16ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D32ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D48ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D64ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D96ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"D2d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D4d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D8d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D16d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D32d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D48d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D64d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D96d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D2ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D4ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D8ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D16ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D32ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D48ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D64ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D96ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D2 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D4 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D8 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D16 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D32 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D48 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D64 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D96 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D2s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D4s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D8s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D16s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D32s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D48s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D64s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"D96s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"FX4mds":           []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"FX12mds":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"FX24mds":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"FX36mds":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"FX48mds":          []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]},
		"E2as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E4as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E8as v5":          []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E16as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E20as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E32as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E48as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E64as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E96as v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E2ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E4ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E8ads v5":         []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E16ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E20ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E32ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E48ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E64ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E96ads v5":        []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"E2d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8d v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E20d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E96d v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E104id v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E2ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8ds v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E20ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E96ds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E104ids v5":       []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E2 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8 v5":            []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E20 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E96 v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E104i v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E2s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8s v5":           []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E20s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E96s v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E104is v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E2bds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4bds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8bds v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16bds v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32bds v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48bds v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64bds v5":        []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E2bs v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E4bs v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E8bs v5":          []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E16bs v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E32bs v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E48bs v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"E64bs v5":         []string{COMPUTE_PROCESSOR_TYPES["ICELAKE"]},
		"NC24ads A100 v4":  []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"NC48ads A100 v4":  []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
		"NC96ads A100 v4":  []string{COMPUTE_PROCESSOR_TYPES["AMD_EPYC_3RD_GEN"]},
	}
)
