package azure_constant_compute_processors

var (
	COMPUTE_PROCESSOR_TYPES = map[string]string{
		// CPU Processors
		"CASCADE_LAKE":     "CASCADE_LAKE",
		"SKYLAKE":          "SKYLAKE",
		"HASWELL":          "HASWELL",
		"BROADWELL":        "BROADWELL",
		"COFFEE_LAKE":      "COFFEE_LAKE",
		"SANDY_BRIDGE":     "SANDY_BRIDGE",
		"IVY_BRIDGE":       "IVY_BRIDGE",
		"ICELAKE":          "ICELAKE",
		"AMD_EPYC_1ST_GEN": "AMD_EPYC_1ST_GEN",
		"AMD_EPYC_2ND_GEN": "AMD_EPYC_2ND_GEN",
		"AMD_EPYC_3RD_GEN": "AMD_EPYC_3RD_GEN",
		"AWS_GRAVITON":     "AWS_GRAVITON",
		"AWS_GRAVITON_2":   "AWS_GRAVITON_2",
		// GPU Processors
		"NVIDIA_K520":         "NVIDIA_K520",
		"NVIDIA_A10G":         "NVIDIA_A10G",
		"NVIDIA_T4":           "NVIDIA_T4",
		"NVIDIA_TESLA_M60":    "NVIDIA_TESLA_M60",
		"NVIDIA_TESLA_K80":    "NVIDIA_TESLA_K80",
		"NVIDIA_TESLA_V100":   "NVIDIA_TESLA_V100",
		"NVIDIA_TESLA_A100":   "NVIDIA_TESLA_A100",
		"NVIDIA_TESLA_P4":     "NVIDIA_TESLA_P4",
		"NVIDIA_TESLA_P40":    "NVIDIA_TESLA_P40",
		"NVIDIA_TESLA_P100":   "NVIDIA_TESLA_P100",
		"AMD_RADEON_PRO_V520": "AMD_RADEON_PRO_V520",
		"XILINX_ALVEO_U250":   "XILINX_ALVEO_U250",
		// Unknown
		"UNKNOWN": "UNKNOWN",
	}
)

func CascadeLakeSkylake() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"], COMPUTE_PROCESSOR_TYPES["SKYLAKE"]}
}

func BroadwellHaswell() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["HASWELL"], COMPUTE_PROCESSOR_TYPES["BROADWELL"]}
}

func BroadwellSkylake() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"], COMPUTE_PROCESSOR_TYPES["SKYLAKE"]}
}

func BroadwelCascadeLake() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["BROADWELL"], COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]}
}

func CascadeLakeSkylakeBroadwellHaswell() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"], COMPUTE_PROCESSOR_TYPES["SKYLAKE"], COMPUTE_PROCESSOR_TYPES["BROADWELL"], COMPUTE_PROCESSOR_TYPES["HASWELL"]}
}

func CascadeLakeSkylakeBroadwell() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"], COMPUTE_PROCESSOR_TYPES["SKYLAKE"], COMPUTE_PROCESSOR_TYPES["BROADWELL"]}
}

func CascadeLakeHaswell() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["HASWELL"], COMPUTE_PROCESSOR_TYPES["CASCADE_LAKE"]}
}

func SkyLakeBroadwellHaswellAMDRome() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"], COMPUTE_PROCESSOR_TYPES["BROADWELL"], COMPUTE_PROCESSOR_TYPES["HASWELL"], COMPUTE_PROCESSOR_TYPES["AMD_EPYC_2ND_GEN"]}
}

func SkyLakeBroadwellHaswellSandyBridgeIvyBridge() []string {
	return []string{COMPUTE_PROCESSOR_TYPES["SKYLAKE"], COMPUTE_PROCESSOR_TYPES["BROADWELL"], COMPUTE_PROCESSOR_TYPES["HASWELL"], COMPUTE_PROCESSOR_TYPES["SANDY_BRIDGE"], COMPUTE_PROCESSOR_TYPES["IVY_BRIDGE"]}
}
