// Because the Consumption Management API returns inconsistent strings for region,
// we need to provide arrays of the possible Options they could be.
package azure_constants

import (
	azure "github.com/tkennes/open-azure-emissions/pkg/azure/models"
)

var (
	// [area, name, semantic_name, Options]
	AZURE_REGIONS = map[string]azure.Region{
		"AF_SOUTH_AFRICA": azure.Region{
			Area:         "Africa regions",
			Name:         "southafrica",
			SemanticName: "AF_SOUTH_AFRICA",
			Options:      []string{"southafrica"},
		},
		"AF_SOUTH_AFRICA_NORTH": azure.Region{
			Area:         "Africa regions",
			Name:         "southafricanorth",
			SemanticName: "AF_SOUTH_AFRICA_NORTH",
			Options:      []string{"southafricanorth"},
		},
		"AF_SOUTH_AFRICA_WEST": azure.Region{
			Area:         "Africa regions",
			Name:         "southafricawest",
			SemanticName: "AF_SOUTH_AFRICA_WEST",
			Options:      []string{"southafricawest"},
		},
		"AP_AUSTRALIA": azure.Region{
			Area:         "APAC regions",
			Name:         "australia",
			SemanticName: "AP_AUSTRALIA",
			Options:      []string{"australia"},
		},
		"AP_AUSTRALIA_CENTRAL": azure.Region{
			Area:         "APAC regions",
			Name:         "australiacentral",
			SemanticName: "AP_AUSTRALIA_CENTRAL",
			Options:      []string{"australiacentral"},
		},
		"AP_AUSTRALIA_CENTRAL2": azure.Region{
			Area:         "APAC regions",
			Name:         "australiacentral2",
			SemanticName: "AP_AUSTRALIA_CENTRAL2",
			Options:      []string{"australiacentral2"},
		},
		"AP_AUSTRALIA_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "australiaeast",
			SemanticName: "AP_AUSTRALIA_EAST",
			Options:      []string{"australiaeast"},
		},
		"AP_AUSTRALIA_SOUTH_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "australiasoutheast",
			SemanticName: "AP_AUSTRALIA_SOUTH_EAST",
			Options:      []string{"australiasoutheast"},
		},
		"AP_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "apeast",
			SemanticName: "AP_EAST",
			Options:      []string{"apeast", "AP East"},
		},
		"AP_SOUTH_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "apsoutheast",
			SemanticName: "AP_SOUTH_EAST",
			Options:      []string{"apsoutheast", "AP Southeast"},
		},
		"AP_JAPAN_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "japaneast",
			SemanticName: "AP_JAPAN_EAST",
			Options:      []string{"japaneast", "JA East"},
		},
		"AP_JAPAN_WEST": azure.Region{
			Area:         "APAC regions",
			Name:         "japanwest",
			SemanticName: "AP_JAPAN_WEST",
			Options:      []string{"japanwest", "JA West"},
		},
		"AP_JAPAN": azure.Region{
			Area:         "APAC regions",
			Name:         "japan",
			SemanticName: "AP_JAPAN",
			Options:      []string{"japan"},
		},
		"AP_KOREA": azure.Region{
			Area:         "APAC regions",
			Name:         "korea",
			SemanticName: "AP_KOREA",
			Options:      []string{"korea"},
		},
		"AP_KOREA_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "koreacentral",
			SemanticName: "AP_KOREA_EAST",
			Options:      []string{"koreacentral", "KR Central"},
		},
		"AP_KOREA_SOUTH": azure.Region{
			Area:         "APAC regions",
			Name:         "koreasouth",
			SemanticName: "AP_KOREA_SOUTH",
			Options:      []string{"koreasouth"},
		},
		"ASIA": azure.Region{
			Area:         "APAC regions",
			Name:         "asia",
			SemanticName: "ASIA",
			Options:      []string{"asia", "Asia"},
		},
		"ASIA_PACIFIC": azure.Region{
			Area:         "APAC regions",
			Name:         "asiapacific",
			SemanticName: "ASIA_PACIFIC",
			Options:      []string{"asiapacific"},
		},
		"ASIA_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "eastasia",
			SemanticName: "ASIA_EAST",
			Options:      []string{"eastasia", "asiaeast"},
		},
		"ASIA_EAST_STAGE": azure.Region{
			Area:         "APAC regions",
			Name:         "eastasiastage",
			SemanticName: "ASIA_EAST_STAGE",
			Options:      []string{"eastasiastage"},
		},
		"ASIA_SOUTH_EAST": azure.Region{
			Area:         "APAC regions",
			Name:         "southeastasia",
			SemanticName: "ASIA_SOUTH_EAST",
			Options:      []string{"southeastasia", "AsiaSouthEast", "asiasoutheast"},
		},
		"ASIA_SOUTH_EAST_STAGE": azure.Region{
			Area:         "APAC regions",
			Name:         "southeastasiastage",
			SemanticName: "ASIA_SOUTH_EAST_STAGE",
			Options:      []string{"southeastasiastage"},
		},
		"INDIA": azure.Region{
			Area:         "APAC regions",
			Name:         "india",
			SemanticName: "INDIA",
			Options:      []string{"india"},
		},
		"IN_CENTRAL": azure.Region{
			Area:         "APAC regions",
			Name:         "centralindia",
			SemanticName: "IN_CENTRAL",
			Options:      []string{"centralindia", "IndiaCentral", "IN Central"},
		},
		"IN_JIO_CENTRAL": azure.Region{
			Area:         "APAC regions",
			Name:         "jioindiacentral",
			SemanticName: "IN_JIO_CENTRAL",
			Options:      []string{"jioindiacentral"},
		},
		"IN_JIO_WEST": azure.Region{
			Area:         "APAC regions",
			Name:         "jioindiawest",
			SemanticName: "IN_JIO_WEST",
			Options:      []string{"jioindiawest"},
		},
		"IN_SOUTH": azure.Region{
			Area:         "APAC regions",
			Name:         "southindia",
			SemanticName: "IN_SOUTH",
			Options:      []string{"southindia"},
		},
		"IN_WEST": azure.Region{
			Area:         "APAC regions",
			Name:         "westindia",
			SemanticName: "IN_WEST",
			Options:      []string{"westindia"},
		},
		"EU_NORTH": azure.Region{
			Area:         "EU regions",
			Name:         "northeurope",
			SemanticName: "EU_NORTH",
			Options:      []string{"northeurope", "europenorth", "NORTHEUROPE", "EU North"},
		},
		"EU_WEST": azure.Region{
			Area:         "EU regions",
			Name:         "westeurope",
			SemanticName: "EU_WEST",
			Options:      []string{"westeurope", "WESTEUROPE", "EU West", "EuropeWest"},
		},
		"EU_FRANCE_CENTRAL": azure.Region{
			Area:         "EU regions",
			Name:         "francecentral",
			SemanticName: "EU_FRANCE_CENTRAL",
			Options:      []string{"francecentral"},
		},
		"EU_FRANCE_SOUTH": azure.Region{
			Area:         "EU regions",
			Name:         "francesouth",
			SemanticName: "EU_FRANCE_SOUTH",
			Options:      []string{"francesouth"},
		},
		"EU_FRANCE": azure.Region{
			Area:         "EU regions",
			Name:         "france",
			SemanticName: "EU_FRANCE",
			Options:      []string{"france"},
		},
		"EU_SWEDEN_CENTRAL": azure.Region{
			Area:         "EU regions",
			Name:         "swedencentral",
			SemanticName: "EU_SWEDEN_CENTRAL",
			Options:      []string{"swedencentral"},
		},
		"EU_SWITZERLAND": azure.Region{
			Area:         "EU regions",
			Name:         "switzerland",
			SemanticName: "EU_SWITZERLAND",
			Options:      []string{"switzerland"},
		},
		"EU_SWITZERLAND_NORTH": azure.Region{
			Area:         "EU regions",
			Name:         "switzerlandnorth",
			SemanticName: "EU_SWITZERLAND_NORTH",
			Options:      []string{"switzerlandnorth"},
		},
		"EU_SWITZERLAND_WEST": azure.Region{
			Area:         "EU regions",
			Name:         "switzerlandwest",
			SemanticName: "EU_SWITZERLAND_WEST",
			Options:      []string{"switzerlandwest"},
		},
		"UK_SOUTH": azure.Region{
			Area:         "EU regions",
			Name:         "uksouth",
			SemanticName: "UK_SOUTH",
			Options:      []string{"uksouth", "UKSOUTH"},
		},
		"UK_WEST": azure.Region{
			Area:         "EU regions",
			Name:         "ukwest",
			SemanticName: "UK_WEST",
			Options:      []string{"ukwest"},
		},
		"EU_GERMANY": azure.Region{
			Area:         "EU regions",
			Name:         "germany",
			SemanticName: "EU_GERMANY",
			Options:      []string{"germany"},
		},
		"EU_GERMANY_NORTH": azure.Region{
			Area:         "EU regions",
			Name:         "germanynorth",
			SemanticName: "EU_GERMANY_NORTH",
			Options:      []string{"germanynorth"},
		},
		"EU_GERMANY_WESTCENTRAL": azure.Region{
			Area:         "EU regions",
			Name:         "germanywestcentral",
			SemanticName: "EU_GERMANY_WESTCENTRAL",
			Options:      []string{"germanywestcentral", "GERMANYWESTCENTRAL", "DE West Central"},
		},
		"EU_NORWAY": azure.Region{
			Area:         "EU regions",
			Name:         "norway",
			SemanticName: "EU_NORWAY",
			Options:      []string{"norway"},
		},
		"EU_NORWAY_EAST": azure.Region{
			Area:         "EU regions",
			Name:         "norwayeast",
			SemanticName: "EU_NORWAY_EAST",
			Options:      []string{"norwayeast"},
		},
		"EU_NORWAY_WEST": azure.Region{
			Area:         "EU regions",
			Name:         "norwaywest",
			SemanticName: "EU_NORWAY_WEST",
			Options:      []string{"norwaywest"},
		},
		"EU_UK": azure.Region{
			Area:         "EU regions",
			Name:         "uk",
			SemanticName: "EU_UK",
			Options:      []string{"uk"},
		},
		"ME_UAE": azure.Region{
			Area:         "Middle East regions",
			Name:         "uae",
			SemanticName: "ME_UAE",
			Options:      []string{"uae"},
		},
		"ME_UAE_CENTRAL": azure.Region{
			Area:         "Middle East regions",
			Name:         "uaecentral",
			SemanticName: "ME_UAE_CENTRAL",
			Options:      []string{"uaecentral"},
		},
		"ME_UAE_NORTH": azure.Region{
			Area:         "Middle East regions",
			Name:         "uaenorth",
			SemanticName: "ME_UAE_NORTH",
			Options:      []string{"uaenorth", "uaen"},
		},
		"ME_QATAR_CENTRAL": azure.Region{
			Area:         "Middle East regions",
			Name:         "qatarcentral",
			SemanticName: "ME_QATAR_CENTRAL",
			Options:      []string{"qatarcentral"},
		},
		"US_CANADA": azure.Region{
			Area:         "America regions",
			Name:         "canada",
			SemanticName: "US_CANADA",
			Options:      []string{"canada"},
		},
		"US_CANADA_CENTRAL": azure.Region{
			Area:         "America regions",
			Name:         "canadacentral",
			SemanticName: "US_CANADA_CENTRAL",
			Options:      []string{"canadacentral"},
		},
		"US_CANADA_EAST": azure.Region{
			Area:         "America regions",
			Name:         "canadaeast",
			SemanticName: "US_CANADA_EAST",
			Options:      []string{"canadaeast"},
		},
		"US_CENTRAL": azure.Region{
			Area:         "America regions",
			Name:         "CentralUS",
			SemanticName: "US_CENTRAL",
			Options:      []string{"CentralUS", "US Central"},
		},
		"US_CENTRAL_EUAP": azure.Region{
			Area:         "America regions",
			Name:         "centraluseuap",
			SemanticName: "US_CENTRAL_EUAP",
			Options:      []string{"centraluseuap"},
		},
		"US_CENTRAL_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "centralusstage",
			SemanticName: "US_CENTRAL_STAGE",
			Options:      []string{"centralusstage"},
		},
		"US_EAST": azure.Region{
			Area:         "America regions",
			Name:         "EastUS",
			SemanticName: "US_EAST",
			Options:      []string{"EastUS", "EASTUS", "USEast", "useast", "US East"},
		},
		"US_EAST_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "eastusstage",
			SemanticName: "US_EAST_STAGE",
			Options:      []string{"eastusstage"},
		},
		"US_EAST_2": azure.Region{
			Area:         "America regions",
			Name:         "EastUS2",
			SemanticName: "US_EAST_2",
			Options:      []string{"EastUS2", "useast2", "US East 2"},
		},
		"US_EAST_2_EUAP": azure.Region{
			Area:         "America regions",
			Name:         "eastus2euap",
			SemanticName: "US_EAST_2_EUAP",
			Options:      []string{"eastus2euap"},
		},
		"US_EAST_2_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "eastus2stage",
			SemanticName: "US_EAST_2_STAGE",
			Options:      []string{"eastus2stage"},
		},
		"US_EAST_3": azure.Region{
			Area:         "America regions",
			Name:         "EastUS3",
			SemanticName: "US_EAST_3",
			Options:      []string{"EastUS3"},
		},
		"US_NORTH_CENTRAL": azure.Region{
			Area:         "America regions",
			Name:         "NorthCentralUs",
			SemanticName: "US_NORTH_CENTRAL",
			Options:      []string{"NorthCentralUs", "northcentralus", "US North Central"},
		},
		"US_NORTH_CENTRAL_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "northcentralusstage",
			SemanticName: "US_NORTH_CENTRAL_STAGE",
			Options:      []string{"northcentralusstage"},
		},
		"US_SOUTH_CENTRAL": azure.Region{
			Area:         "America regions",
			Name:         "SouthCentralUS",
			SemanticName: "US_SOUTH_CENTRAL",
			Options:      []string{"SouthCentralUS"},
		},
		"US_SOUTH_CENTRAL_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "southcentralusstage",
			SemanticName: "US_SOUTH_CENTRAL_STAGE",
			Options:      []string{"southcentralusstage"},
		},
		"US_US": azure.Region{
			Area:         "America regions",
			Name:         "unitedstates",
			SemanticName: "US_US",
			Options:      []string{"unitedstates"},
		},
		"US_US_EAP": azure.Region{
			Area:         "America regions",
			Name:         "unitedstateseuap",
			SemanticName: "US_US_EAP",
			Options:      []string{"unitedstateseuap"},
		},
		"US_WEST_CENTRAL": azure.Region{
			Area:         "America regions",
			Name:         "WestCentralUS",
			SemanticName: "US_WEST_CENTRAL",
			Options:      []string{"WestCentralUS", "westcentralus", "US West Central"},
		},
		"US_NORTH": azure.Region{
			Area:         "America regions",
			Name:         "USNorth",
			SemanticName: "US_NORTH",
			Options:      []string{"USNorth"},
		},
		"US_WEST": azure.Region{
			Area:         "America regions",
			Name:         "WestUS",
			SemanticName: "US_WEST",
			Options:      []string{"WestUS", "westus", "US West"},
		},
		"US_WEST_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "westusstage",
			SemanticName: "US_WEST_STAGE",
			Options:      []string{"westusstage"},
		},
		"US_WEST_2": azure.Region{
			Area:         "America regions",
			Name:         "westus2",
			SemanticName: "US_WEST_2",
			Options:      []string{"westus2", "uswest2", "WESTUS2", "US West 2"},
		},
		"US_WEST_2_STAGE": azure.Region{
			Area:         "America regions",
			Name:         "westus2stage",
			SemanticName: "US_WEST_2_STAGE",
			Options:      []string{"westus2stage"},
		},
		"US_WEST_3": azure.Region{
			Area:         "America regions",
			Name:         "westus3",
			SemanticName: "US_WEST_3",
			Options:      []string{"westus3", "uswest3"},
		},
		"BRAZIL": azure.Region{
			Area:         "America regions",
			Name:         "brazil",
			SemanticName: "BRAZIL",
			Options:      []string{"brazil"},
		},
		"BRAZIL_SOUTH": azure.Region{
			Area:         "America regions",
			Name:         "brazilsouth",
			SemanticName: "BRAZIL_SOUTH",
			Options:      []string{"brazilsouth"},
		},
		"BRAZIL_SOUTH_EAST": azure.Region{
			Area:         "America regions",
			Name:         "brazilsoutheast",
			SemanticName: "BRAZIL_SOUTH_EAST",
			Options:      []string{"brazilsoutheast"},
		},
		"ALL": azure.Region{
			Area:         "Other azure.Regions",
			Name:         "All azure.Regions",
			SemanticName: "ALL",
			Options:      []string{"All azure.Regions", "GLOBAL", "Intercontinental"},
		},
		"UNASSIGNED": azure.Region{
			Area:         "Other azure.Regions",
			Name:         "Unassigned",
			SemanticName: "UNASSIGNED",
			Options:      []string{"Unassigned"},
		},
		"UNKNOWN": azure.Region{
			Area:         "Other azure.Regions",
			Name:         "Unknown",
			SemanticName: "UNKNOWN",
			Options:      []string{"Unknown"},
		},
	}
)
