package azure_constants_meters

var (
	ESTIMABLE_METER_CATEGORIES = []string{
		// Compute and Memory
		"Azure App Service",
		"Virtual Machines",

		// Memory
		"Redis Cache",

		// Storage
		"Storage",
		"Container Registry",

		// Networking
		"Azure Front Door Service",
		"Bandwidth",
		"Azure Bastion",
		"Load Balancer",
		"Azure Firewall",

		// To do: add the following categories
		// "Specialized Compute",
	}

	UNESTIMABLE_METER_CATEGORIES = []string{
		"API Management",
		"Advanced Threat Protection",
		"App Center",
		"Application Gateway",
		"Application Insights",
		"Automation",
		"Azure Active Directory B2C",
		"Azure Active Directory Domain Services",
		"Azure Analysis Services",
		"Azure Bot Service",
		"Azure Container Service",
		"Azure Cosmos DB",
		"Azure DDOS Protection",
		"Azure DNS",
		"Azure Data Factory",
		"Azure Data Factory v2",
		"Azure Database Migration Service",
		"Azure Database for MariaDB",
		"Azure Database for MySQL",
		"Azure Database for PostgreSQL",
		"Azure Databricks",
		"Azure DevOps",
		"Azure Lab Services",
		"Azure Maps",
		"Azure Monitor",
		"Azure Search",
		"Azure Site Recovery",
		"Azure Stack",
		"Backup",
		"BizTalk Services",
		"Cloud Services",
		"Cognitive Services",
		"Container Instances",
		"Content Delivery Network",
		"Data Box",
		"Data Catalog",
		"Data Lake Analytics",
		"Data Lake Store",
		"Datacenter Capacity",
		"Dynamics 365 for Customer Insights",
		"Event Grid",
		"Event Hubs",
		"ExpressRoute",
		"Functions",
		"HDInsight",
		"Insight and Analytics",
		"IoT Central",
		"IoT Hub",
		"Key Vault",
		"Log Analytics",
		"Logic Apps",
		"Machine Learning Service",
		"Machine Learning Studio",
		"Media Services",
		"Microsoft Genomics",
		"Multi-Factor Authentication",
		"MySQL Database on Azure",
		"Network Watcher",
		"Notification Hubs",
		"Power BI Embedded",
		"SQL Advanced Threat Protection",
		"SQL Data Warehouse",
		"SQL Database",
		"SQL Server Stretch Database",
		"Scheduler",
		"Security Center",
		"Service Bus",
		"Service Fabric",
		"Service Fabric Mesh",
		"SignalR",
		"Sonar DaaS",
		"StorSimple",
		"Stream Analytics",
		"Time Series Insights",
		"Traffic Manager",
		"VPN Gateway",
		"Virtual Machines Licenses",
		"Virtual Network",
		"Virtual WAN",
		"Visual Studio Subscription",
		"Windows 10 IoT Core Services",
		"Xamarin University",
	}
)
