package azure_constants

import (
	azure "github.com/tkennes/open-azure-emissions/pkg/azure/models"
)

var (
	VIRTUAL_MACHINE_TYPE_CONSTRAINED_VCPU_CAPABLE_MAPPING = map[string]azure.VirtualMachineVCPUConstraint{
		"DS11-1 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS11-1 v2",
			VCPUs:               1,
			Memory:              14,
			HighestVCPUPossible: 2,
			EmbodiedEmissions:   1.15,
		},
		"DS12-1 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS12-1 v2",
			VCPUs:               1,
			Memory:              28,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1666,
		},
		"DS12-2 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS12-2 v2",
			VCPUs:               2,
			Memory:              28,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1666,
		},
		"DS13-2 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS13-2 v2",
			VCPUs:               2,
			Memory:              56,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2055,
		},
		"DS13-4 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS13-4 v2",
			VCPUs:               4,
			Memory:              56,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2055,
		},
		"DS14-4 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS14-4 v2",
			VCPUs:               4,
			Memory:              112,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.2831,
		},
		"DS14-8 v2": azure.VirtualMachineVCPUConstraint{
			Name:                "DS14-8 v2",
			VCPUs:               8,
			Memory:              112,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.2831,
		},
		"E4-2as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E4-2as v4",
			VCPUs:               2,
			Memory:              32,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1722,
		},
		"E4-2ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E4-2ds v4",
			VCPUs:               2,
			Memory:              32,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1722,
		},
		"E4-2s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E4-2s v3",
			VCPUs:               2,
			Memory:              32,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1722,
		},
		"E4-2s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E4-2s v4",
			VCPUs:               2,
			Memory:              32,
			HighestVCPUPossible: 4,
			EmbodiedEmissions:   1.1222,
		},
		"E8-2as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-2as v4",
			VCPUs:               2,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-2ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-2ds v4",
			VCPUs:               2,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-2s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-2s v3",
			VCPUs:               2,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-2s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-2s v4",
			VCPUs:               2,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.1666,
		},
		"E8-4as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-4as v4",
			VCPUs:               4,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-4ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-4ds v4",
			VCPUs:               4,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-4s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-4s v3",
			VCPUs:               4,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.2166,
		},
		"E8-4s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E8-4s v4",
			VCPUs:               4,
			Memory:              64,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.1666,
		},
		"E16-4as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-4as v4",
			VCPUs:               4,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-4ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-4ds v4",
			VCPUs:               4,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-4s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-4s v3",
			VCPUs:               4,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-4s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-4s v4",
			VCPUs:               4,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.2553,
		},
		"M8-2ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M8-2ms",
			VCPUs:               2,
			Memory:              219,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.4315,
		},
		"M8-4ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M8-4ms",
			VCPUs:               4,
			Memory:              219,
			HighestVCPUPossible: 8,
			EmbodiedEmissions:   1.4315,
		},
		"Gs4-4": azure.VirtualMachineVCPUConstraint{
			Name:                "Gs4-4",
			VCPUs:               4,
			Memory:              224,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.4385,
		},
		"Gs4-8": azure.VirtualMachineVCPUConstraint{
			Name:                "Gs4-8",
			VCPUs:               8,
			Memory:              224,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.4385,
		},
		"M16-4ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M16-4ms",
			VCPUs:               4,
			Memory:              438,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.7353,
		},
		"M16-8ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M16-8ms",
			VCPUs:               8,
			Memory:              438,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.7353,
		},
		"E16-8as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-8as v4",
			VCPUs:               8,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-8ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-8ds v4",
			VCPUs:               8,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-8s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-8s v3",
			VCPUs:               8,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.3053,
		},
		"E16-8s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E16-8s v4",
			VCPUs:               8,
			Memory:              128,
			HighestVCPUPossible: 16,
			EmbodiedEmissions:   1.2553,
		},
		"E32-8as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-8as v4",
			VCPUs:               8,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-8ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-8ds v4",
			VCPUs:               8,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-8s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-8s v3",
			VCPUs:               8,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-8s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-8s v4",
			VCPUs:               8,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4329,
		},
		"Gs5-8": azure.VirtualMachineVCPUConstraint{
			Name:                "Gs5-8",
			VCPUs:               8,
			Memory:              448,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.7491,
		},
		"Gs5-16": azure.VirtualMachineVCPUConstraint{
			Name:                "Gs5-16",
			VCPUs:               16,
			Memory:              448,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.7491,
		},
		"M32-8ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M32-8ms",
			VCPUs:               8,
			Memory:              875,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   2.3413,
		},
		"E32-16as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-16as v4",
			VCPUs:               16,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-16ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-16ds v4",
			VCPUs:               16,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-16s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-16s v3",
			VCPUs:               16,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4829,
		},
		"E32-16s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E32-16s v4",
			VCPUs:               16,
			Memory:              256,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   1.4329,
		},
		"E64-16s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-16s v3",
			VCPUs:               16,
			Memory:              432,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.727,
		},
		"E64-32s v3": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-32s v3",
			VCPUs:               32,
			Memory:              432,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.727,
		},
		"HB120-16rs v3": azure.VirtualMachineVCPUConstraint{
			Name:                "HB120-16rs v3",
			VCPUs:               16,
			Memory:              448,
			HighestVCPUPossible: 120,
			EmbodiedEmissions:   1.6991,
		},
		"HB120-32rs v3": azure.VirtualMachineVCPUConstraint{
			Name:                "HB120-32rs v3",
			VCPUs:               32,
			Memory:              448,
			HighestVCPUPossible: 120,
			EmbodiedEmissions:   1.6991,
		},
		"HB120-64rs v3": azure.VirtualMachineVCPUConstraint{
			Name:                "HB120-64rs v3",
			VCPUs:               64,
			Memory:              448,
			HighestVCPUPossible: 120,
			EmbodiedEmissions:   1.6991,
		},
		"HB120-96rs v3": azure.VirtualMachineVCPUConstraint{
			Name:                "HB120-96rs v3",
			VCPUs:               96,
			Memory:              448,
			HighestVCPUPossible: 120,
			EmbodiedEmissions:   1.6991,
		},
		"E64-16ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-16ds v4",
			VCPUs:               16,
			Memory:              504,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.8268,
		},
		"E64-16s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-16s v4",
			VCPUs:               16,
			Memory:              504,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.7768,
		},
		"E64-16as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-16as v4",
			VCPUs:               16,
			Memory:              512,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.8379,
		},
		"M32-16ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M32-16ms",
			VCPUs:               16,
			Memory:              875,
			HighestVCPUPossible: 32,
			EmbodiedEmissions:   2.3413,
		},
		"M64-16ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M64-16ms",
			VCPUs:               16,
			Memory:              1750,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   3.5549,
		},
		"E96-24as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E96-24as v4",
			VCPUs:               24,
			Memory:              672,
			HighestVCPUPossible: 96,
			EmbodiedEmissions:   2.0598,
		},
		"E64-32ds v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-32ds v4",
			VCPUs:               32,
			Memory:              504,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.8268,
		},
		"E64-32s v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-32s v4",
			VCPUs:               32,
			Memory:              504,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.7768,
		},
		"E64-32as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E64-32as v4",
			VCPUs:               32,
			Memory:              512,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   1.8379,
		},
		"M64-32ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M64-32ms",
			VCPUs:               32,
			Memory:              1750,
			HighestVCPUPossible: 64,
			EmbodiedEmissions:   3.5549,
		},
		"M128-32ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M128-32ms",
			VCPUs:               32,
			Memory:              3800,
			HighestVCPUPossible: 128,
			EmbodiedEmissions:   6.398,
		},
		"E96-48as v4": azure.VirtualMachineVCPUConstraint{
			Name:                "E96-48as v4",
			VCPUs:               48,
			Memory:              672,
			HighestVCPUPossible: 96,
			EmbodiedEmissions:   2.0598,
		},
		"M128-64ms": azure.VirtualMachineVCPUConstraint{
			Name:                "M128-64ms",
			VCPUs:               64,
			Memory:              3800,
			HighestVCPUPossible: 128,
			EmbodiedEmissions:   6.398,
		},
	}
)
