package azure_services

import (
	azure_models "github.com/tkennes/open-azure-emissions/pkg/azure/models"
)

var (
	// [vcpus, memory, embodied emissions]
	VIRTUAL_MACHINE_TYPES = map[string]azure_models.VirtualMachine{
		// As-series
		"A0": azure_models.VirtualMachine{
			Name:   "A0",
			Series: "As-series",
			VCPUs:  1,
			Memory: 0.75,
		},
		"A1": azure_models.VirtualMachine{
			Name:   "A1",
			Series: "As-series",
			VCPUs:  1,
			Memory: 1.75,
		},
		"A2": azure_models.VirtualMachine{
			Name:   "A2",
			Series: "As-series",
			VCPUs:  2,
			Memory: 3.5,
		},
		"A3": azure_models.VirtualMachine{
			Name:   "A3",
			Series: "As-series",
			VCPUs:  4,
			Memory: 7,
		},
		"A4": azure_models.VirtualMachine{
			Name:   "A4",
			Series: "As-series",
			VCPUs:  8,
			Memory: 14,
		},
		// Bs-series
		"B1Ls": azure_models.VirtualMachine{
			Name:              "B1Ls",
			Series:            "Bs-series",
			VCPUs:             1,
			Memory:            0.5,
			EmbodiedEmissions: 1.2388,
		},
		"B1s": azure_models.VirtualMachine{
			Name:              "B1s",
			Series:            "Bs-series",
			VCPUs:             1,
			Memory:            1,
			EmbodiedEmissions: 1.2388,
		},
		"B1Ms": azure_models.VirtualMachine{
			Name:              "B1Ms",
			Series:            "Bs-series",
			VCPUs:             1,
			Memory:            2,
			EmbodiedEmissions: 1.2388,
		},
		"B2s": azure_models.VirtualMachine{
			Name:              "B2s",
			Series:            "Bs-series",
			VCPUs:             2,
			Memory:            4,
			EmbodiedEmissions: 1.2388,
		},
		"B2ms": azure_models.VirtualMachine{
			Name:              "B2ms",
			Series:            "Bs-series",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.2388,
		},
		"B4ms": azure_models.VirtualMachine{
			Name:              "B4ms",
			Series:            "Bs-series",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.2388,
		},
		"B8ms": azure_models.VirtualMachine{
			Name:              "B8ms",
			Series:            "Bs-series",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.2388,
		},
		"B12ms": azure_models.VirtualMachine{
			Name:              "B12ms",
			Series:            "Bs-series",
			VCPUs:             12,
			Memory:            48,
			EmbodiedEmissions: 1.2388,
		},
		"B16ms": azure_models.VirtualMachine{
			Name:              "B16ms",
			Series:            "Bs-series",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.2388,
		},
		"B20ms": azure_models.VirtualMachine{
			Name:              "B20ms",
			Series:            "Bs-series",
			VCPUs:             20,
			Memory:            80,
			EmbodiedEmissions: 1.2388,
		},
		// Av2 Standard
		"A1 v2": azure_models.VirtualMachine{
			Name:              "A1 v2",
			Series:            "Av2 Standard",
			VCPUs:             1,
			Memory:            2,
			EmbodiedEmissions: 1.2166,
		},
		"A2 v2": azure_models.VirtualMachine{
			Name:              "A2 v2",
			Series:            "Av2 Standard",
			VCPUs:             2,
			Memory:            4,
			EmbodiedEmissions: 1.2166,
		},
		"A2m v2": azure_models.VirtualMachine{
			Name:              "A2m v2",
			Series:            "Av2 Standard",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.2166,
		},
		"A4 v2": azure_models.VirtualMachine{
			Name:              "A4 v2",
			Series:            "Av2 Standard",
			VCPUs:             4,
			Memory:            8,
			EmbodiedEmissions: 1.2166,
		},
		"A4m v2": azure_models.VirtualMachine{
			Name:              "A4m v2",
			Series:            "Av2 Standard",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.2166,
		},
		"A8 v2": azure_models.VirtualMachine{
			Name:              "A8 v2",
			Series:            "Av2 Standard",
			VCPUs:             8,
			Memory:            16,
			EmbodiedEmissions: 1.2166,
		},
		"A8m v2": azure_models.VirtualMachine{
			Name:              "A8m v2",
			Series:            "Av2 Standard",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.2166,
		},
		// D2a – D96a v4
		"D2a v4": azure_models.VirtualMachine{
			Name:              "D2a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5604,
		},
		"D4a v4": azure_models.VirtualMachine{
			Name:              "D4a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5604,
		},
		"D8a v4": azure_models.VirtualMachine{
			Name:              "D8a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5604,
		},
		"D16a v4": azure_models.VirtualMachine{
			Name:              "D16a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5604,
		},
		"D32a v4": azure_models.VirtualMachine{
			Name:              "D32a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5604,
		},
		"D48a v4": azure_models.VirtualMachine{
			Name:              "D48a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5604,
		},
		"D64a v4": azure_models.VirtualMachine{
			Name:              "D64a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5604,
		},
		"D96a v4": azure_models.VirtualMachine{
			Name:              "D96a v4",
			Series:            "D2a – D96a v4",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.5604,
		},
		// D2as – D96as v4
		"D2as v4": azure_models.VirtualMachine{
			Name:              "D2as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5604,
		},
		"D4as v4": azure_models.VirtualMachine{
			Name:              "D4as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5604,
		},
		"D8as v4": azure_models.VirtualMachine{
			Name:              "D8as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5604,
		},
		"D16as v4": azure_models.VirtualMachine{
			Name:              "D16as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5604,
		},
		"D32as v4": azure_models.VirtualMachine{
			Name:              "D32as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5604,
		},
		"D48as v4": azure_models.VirtualMachine{
			Name:              "D48as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5604,
		},
		"D64as v4": azure_models.VirtualMachine{
			Name:              "D64as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5604,
		},
		"D96as v4": azure_models.VirtualMachine{
			Name:              "D96as v4",
			Series:            "D2as – D96as v4",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.5604,
		},
		// D2d – D64d v4
		"D2d v4": azure_models.VirtualMachine{
			Name:              "D2d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.4829,
		},
		"D4d v4": azure_models.VirtualMachine{
			Name:              "D4d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.4829,
		},
		"D8d v4": azure_models.VirtualMachine{
			Name:              "D8d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.4829,
		},
		"D16d v4": azure_models.VirtualMachine{
			Name:              "D16d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.4829,
		},
		"D32d v4": azure_models.VirtualMachine{
			Name:              "D32d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.4829,
		},
		"D48d v4": azure_models.VirtualMachine{
			Name:              "D48d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.4829,
		},
		"D64d v4": azure_models.VirtualMachine{
			Name:              "D64d v4",
			Series:            "D2d – D64d v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.4829,
		},
		// D2ds – D64ds v4
		"D2ds v4": azure_models.VirtualMachine{
			Name:              "D2ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5329,
		},
		"D4ds v4": azure_models.VirtualMachine{
			Name:              "D4ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5329,
		},
		"D8ds v4": azure_models.VirtualMachine{
			Name:              "D8ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5329,
		},
		"D16ds v4": azure_models.VirtualMachine{
			Name:              "D16ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5329,
		},
		"D32ds v4": azure_models.VirtualMachine{
			Name:              "D32ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5329,
		},
		"D48ds v4": azure_models.VirtualMachine{
			Name:              "D48ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5329,
		},
		"D64ds v4": azure_models.VirtualMachine{
			Name:              "D64ds v4",
			Series:            "D2ds – D64ds v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5329,
		},
		// D2 – D64 v4
		"D2 v4": azure_models.VirtualMachine{
			Name:              "D2 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.4329,
		},
		"D4 v4": azure_models.VirtualMachine{
			Name:              "D4 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.4329,
		},
		"D8 v4": azure_models.VirtualMachine{
			Name:              "D8 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.4329,
		},
		"D16 v4": azure_models.VirtualMachine{
			Name:              "D16 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.4329,
		},
		"D32 v4": azure_models.VirtualMachine{
			Name:              "D32 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.4329,
		},
		"D48 v4": azure_models.VirtualMachine{
			Name:              "D48 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.4329,
		},
		"D64 v4": azure_models.VirtualMachine{
			Name:              "D64 v4",
			Series:            "D2 – D64 v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.4329,
		},
		// D2s – D64s v4
		"D2s v4": azure_models.VirtualMachine{
			Name:              "D2s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.4329,
		},
		"D4s v4": azure_models.VirtualMachine{
			Name:              "D4s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.4329,
		},
		"D8s v4": azure_models.VirtualMachine{
			Name:              "D8s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.4329,
		},
		"D16s v4": azure_models.VirtualMachine{
			Name:              "D16s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5079,
		},
		"D32s v4": azure_models.VirtualMachine{
			Name:              "D32s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.4329,
		},
		"D48s v4": azure_models.VirtualMachine{
			Name:              "D48s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.4329,
		},
		"D64s v4": azure_models.VirtualMachine{
			Name:              "D64s v4",
			Series:            "D2s – D64s v4",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.4329,
		},
		// D2-64 v3
		"D2 v3": azure_models.VirtualMachine{
			Name:              "D2 v3",
			Series:            "D2-64 v3",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.4829,
		},
		"D4 v3": azure_models.VirtualMachine{
			Name:              "D4 v3",
			Series:            "D2-64 v3",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.4829,
		},
		"D8 v3": azure_models.VirtualMachine{
			Name:              "D8 v3",
			Series:            "D2-64 v3",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.4829,
		},
		"D16 v3": azure_models.VirtualMachine{
			Name:              "D16 v3",
			Series:            "D2-64 v3",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.4454,
		},
		"D32 v3": azure_models.VirtualMachine{
			Name:              "D32 v3",
			Series:            "D2-64 v3",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.4829,
		},
		"D48 v3": azure_models.VirtualMachine{
			Name:              "D48 v3",
			Series:            "D2-64 v3",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.4829,
		},
		"D64 v3": azure_models.VirtualMachine{
			Name:              "D64 v3",
			Series:            "D2-64 v3",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.4829,
		},
		// D2s-64s v3
		"D2s v3": azure_models.VirtualMachine{
			Name:              "D2s v3",
			Series:            "D2s-64s v3",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.4829,
		},
		"D4s v3": azure_models.VirtualMachine{
			Name:              "D4s v3",
			Series:            "D2s-64s v3",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.4829,
		},
		"D8s v3": azure_models.VirtualMachine{
			Name:              "D8s v3",
			Series:            "D2s-64s v3",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.4829,
		},
		"D16s v3": azure_models.VirtualMachine{
			Name:              "D16s v3",
			Series:            "D2s-64s v3",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.4454,
		},
		"D32s v3": azure_models.VirtualMachine{
			Name:              "D32s v3",
			Series:            "D2s-64s v3",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.4829,
		},
		"D48s v3": azure_models.VirtualMachine{
			Name:              "D48s v3",
			Series:            "D2s-64s v3",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.4829,
		},
		"D64s v3": azure_models.VirtualMachine{
			Name:              "D64s v3",
			Series:            "D2s-64s v3",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.4829,
		},
		// D1-5 v2
		"D1 v2": azure_models.VirtualMachine{
			Name:              "D1 v2",
			Series:            "D1-5 v2",
			VCPUs:             1,
			Memory:            3.5,
			EmbodiedEmissions: 1.9059,
		},
		"D2 v2": azure_models.VirtualMachine{
			Name:              "D2 v2",
			Series:            "D1-5 v2",
			VCPUs:             2,
			Memory:            7,
			EmbodiedEmissions: 1.2055,
		},
		"D3 v2": azure_models.VirtualMachine{
			Name:              "D3 v2",
			Series:            "D1-5 v2",
			VCPUs:             4,
			Memory:            14,
			EmbodiedEmissions: 1.2055,
		},
		"D4 v2": azure_models.VirtualMachine{
			Name:              "D4 v2",
			Series:            "D1-5 v2",
			VCPUs:             8,
			Memory:            28,
			EmbodiedEmissions: 1.2055,
		},
		"D5 v2": azure_models.VirtualMachine{
			Name:              "D5 v2",
			Series:            "D1-5 v2",
			VCPUs:             16,
			Memory:            56,
			EmbodiedEmissions: 1.2055,
		},
		// D1s-5s v2
		"Ds1 v2": azure_models.VirtualMachine{
			Name:              "Ds1 v2",
			Series:            "D1s-5s v2",
			VCPUs:             1,
			Memory:            3.5,
			EmbodiedEmissions: 1.3054,
		},
		"Ds2 v2": azure_models.VirtualMachine{
			Name:              "Ds2 v2",
			Series:            "D1s-5s v2",
			VCPUs:             2,
			Memory:            7,
			EmbodiedEmissions: 1.2555,
		},
		"Ds3 v2": azure_models.VirtualMachine{
			Name:              "Ds3 v2",
			Series:            "D1s-5s v2",
			VCPUs:             4,
			Memory:            14,
			EmbodiedEmissions: 1.2555,
		},
		"Ds4 v2": azure_models.VirtualMachine{
			Name:              "Ds4 v2",
			Series:            "D1s-5s v2",
			VCPUs:             8,
			Memory:            28,
			EmbodiedEmissions: 1.2555,
		},
		"Ds5 v2": azure_models.VirtualMachine{
			Name:              "Ds5 v2",
			Series:            "D1s-5s v2",
			VCPUs:             16,
			Memory:            56,
			EmbodiedEmissions: 1.2555,
		},
		// DCsv2-series
		"DC1s v2": azure_models.VirtualMachine{
			Name:              "DC1s v2",
			Series:            "DCsv2-series",
			VCPUs:             1,
			Memory:            4,
			EmbodiedEmissions: 1.1722,
		},
		"DC2s v2": azure_models.VirtualMachine{
			Name:              "DC2s v2",
			Series:            "DCsv2-series",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.1722,
		},
		"DC4s v2": azure_models.VirtualMachine{
			Name:              "DC4s v2",
			Series:            "DCsv2-series",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.1722,
		},
		"DC8 v2": azure_models.VirtualMachine{
			Name:              "DC8 v2",
			Series:            "DCsv2-series",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.1722,
		},
		// Fsv2-series
		"F2s v2": azure_models.VirtualMachine{
			Name:              "F2s v2",
			Series:            "Fsv2-series",
			VCPUs:             2,
			Memory:            4,
			EmbodiedEmissions: 1.3775,
		},
		"F4s v2": azure_models.VirtualMachine{
			Name:              "F4s v2",
			Series:            "Fsv2-series",
			VCPUs:             4,
			Memory:            8,
			EmbodiedEmissions: 1.3775,
		},
		"F8s v2": azure_models.VirtualMachine{
			Name:              "F8s v2",
			Series:            "Fsv2-series",
			VCPUs:             8,
			Memory:            16,
			EmbodiedEmissions: 1.5883,
		},
		"F16s v2": azure_models.VirtualMachine{
			Name:              "F16s v2",
			Series:            "Fsv2-series",
			VCPUs:             16,
			Memory:            32,
			EmbodiedEmissions: 1.2999,
		},
		"F32s v2": azure_models.VirtualMachine{
			Name:              "F32s v2",
			Series:            "Fsv2-series",
			VCPUs:             32,
			Memory:            64,
			EmbodiedEmissions: 1.3775,
		},
		"F48s v2": azure_models.VirtualMachine{
			Name:              "F48s v2",
			Series:            "Fsv2-series",
			VCPUs:             48,
			Memory:            96,
			EmbodiedEmissions: 1.3775,
		},
		"F64s v2": azure_models.VirtualMachine{
			Name:              "F64s v2",
			Series:            "Fsv2-series",
			VCPUs:             64,
			Memory:            128,
			EmbodiedEmissions: 1.3775,
		},
		"F72s v2": azure_models.VirtualMachine{
			Name:              "F72s v2",
			Series:            "Fsv2-series",
			VCPUs:             72,
			Memory:            144,
			EmbodiedEmissions: 1.3775,
		},
		// F-series
		"F1": azure_models.VirtualMachine{
			Name:              "F1",
			Series:            "F-series",
			VCPUs:             1,
			Memory:            2,
			EmbodiedEmissions: 1.6383,
		},
		"F2": azure_models.VirtualMachine{
			Name:              "F2",
			Series:            "F-series",
			VCPUs:             2,
			Memory:            4,
			EmbodiedEmissions: 1.2222,
		},
		"F4": azure_models.VirtualMachine{
			Name:              "F4",
			Series:            "F-series",
			VCPUs:             4,
			Memory:            8,
			EmbodiedEmissions: 1.2222,
		},
		"F8": azure_models.VirtualMachine{
			Name:              "F8",
			Series:            "F-series",
			VCPUs:             8,
			Memory:            16,
			EmbodiedEmissions: 1.2222,
		},
		"F16": azure_models.VirtualMachine{
			Name:              "F16",
			Series:            "F-series",
			VCPUs:             16,
			Memory:            32,
			EmbodiedEmissions: 1.2222,
		},
		// Fs-Series
		"F1s": azure_models.VirtualMachine{
			Name:              "F1s",
			Series:            "Fs-Series",
			VCPUs:             1,
			Memory:            2,
			EmbodiedEmissions: 1.2222,
		},
		"F2s": azure_models.VirtualMachine{
			Name:              "F2s",
			Series:            "Fs-Series",
			VCPUs:             2,
			Memory:            4,
			EmbodiedEmissions: 1.2222,
		},
		"F4s": azure_models.VirtualMachine{
			Name:              "F4s",
			Series:            "Fs-Series",
			VCPUs:             4,
			Memory:            8,
			EmbodiedEmissions: 1.2222,
		},
		"F8s": azure_models.VirtualMachine{
			Name:              "F8s",
			Series:            "Fs-Series",
			VCPUs:             8,
			Memory:            16,
			EmbodiedEmissions: 1.2222,
		},
		"F16s": azure_models.VirtualMachine{
			Name:              "F16s",
			Series:            "Fs-Series",
			VCPUs:             16,
			Memory:            32,
			EmbodiedEmissions: 1.2222,
		},
		// E2a – E96a v4
		"E2a v4": azure_models.VirtualMachine{
			Name:              "E2a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.9598,
		},
		"E4a v4": azure_models.VirtualMachine{
			Name:              "E4a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.9598,
		},
		"E8a v4": azure_models.VirtualMachine{
			Name:              "E8a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.9598,
		},
		"E16a v4": azure_models.VirtualMachine{
			Name:              "E16a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.9598,
		},
		"E20a v4": azure_models.VirtualMachine{
			Name:              "E20a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.9598,
		},
		"E32a v4": azure_models.VirtualMachine{
			Name:              "E32a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.9598,
		},
		"E48a v4": azure_models.VirtualMachine{
			Name:              "E48a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.9598,
		},
		"E64a v4": azure_models.VirtualMachine{
			Name:              "E64a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 1.9598,
		},
		"E96a v4": azure_models.VirtualMachine{
			Name:              "E96a v4",
			Series:            "E2a – E96a v4",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 1.9598,
		},
		// E2as – E96as v4
		"E2as v4": azure_models.VirtualMachine{
			Name:              "E2as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.0098,
		},
		"E4as v4": azure_models.VirtualMachine{
			Name:              "E4as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.0098,
		},
		"E8as v4": azure_models.VirtualMachine{
			Name:              "E8as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0098,
		},
		"E16as v4": azure_models.VirtualMachine{
			Name:              "E16as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0098,
		},
		"E20as v4": azure_models.VirtualMachine{
			Name:              "E20as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 2.0098,
		},
		"E32as v4": azure_models.VirtualMachine{
			Name:              "E32as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0098,
		},
		"E48as v4": azure_models.VirtualMachine{
			Name:              "E48as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0098,
		},
		"E64as v4": azure_models.VirtualMachine{
			Name:              "E64as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.0098,
		},
		"E96as v4": azure_models.VirtualMachine{
			Name:              "E96as v4",
			Series:            "E2as – E96as v4",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		// E2 – E96 v5
		// "E2 v5": azure_models.VirtualMachine{
		// 	Name:              "E2 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             2,
		// 	Memory:            16,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E4 v5": azure_models.VirtualMachine{
		// 	Name:              "E4 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             4,
		// 	Memory:            32,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E8 v5": azure_models.VirtualMachine{
		// 	Name:              "E8 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             8,
		// 	Memory:            64,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E16 v5": azure_models.VirtualMachine{
		// 	Name:              "E16 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             16,
		// 	Memory:            128,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E20 v5": azure_models.VirtualMachine{
		// 	Name:              "E20 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             20,
		// 	Memory:            160,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E32 v5": azure_models.VirtualMachine{
		// 	Name:              "E32 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             32,
		// 	Memory:            256,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E48 v5": azure_models.VirtualMachine{
		// 	Name:              "E48 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             48,
		// 	Memory:            384,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E64 v5": azure_models.VirtualMachine{
		// 	Name:              "E64 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             64,
		// 	Memory:            512,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// "E96 v5": azure_models.VirtualMachine{
		// 	Name:              "E96 v5",
		// 	Series:            "E2 – E96 v5",
		// 	VCPUs:             96,
		// 	Memory:            672,
		// 	EmbodiedEmissions: 2.0098,
		// },
		// E2d – E64d v4
		"E2d v4": azure_models.VirtualMachine{
			Name:              "E2d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.8768,
		},
		"E4d v4": azure_models.VirtualMachine{
			Name:              "E4d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.8768,
		},
		"E8d v4": azure_models.VirtualMachine{
			Name:              "E8d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.8768,
		},
		"E16d v4": azure_models.VirtualMachine{
			Name:              "E16d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.8768,
		},
		"E20d v4": azure_models.VirtualMachine{
			Name:              "E20d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.8768,
		},
		"E32d v4": azure_models.VirtualMachine{
			Name:              "E32d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.8768,
		},
		"E48d v4": azure_models.VirtualMachine{
			Name:              "E48d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.8768,
		},
		"E64d v4": azure_models.VirtualMachine{
			Name:              "E64d v4",
			Series:            "E2d – E64d v4",
			VCPUs:             64,
			Memory:            504,
			EmbodiedEmissions: 1.8768,
		},
		// E2ds – E64ds v4
		"E2ds v4": azure_models.VirtualMachine{
			Name:              "E2ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.8768,
		},
		"E4ds v4": azure_models.VirtualMachine{
			Name:              "E4ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.8768,
		},
		"E8ds v4": azure_models.VirtualMachine{
			Name:              "E8ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.8768,
		},
		"E16ds v4": azure_models.VirtualMachine{
			Name:              "E16ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.8768,
		},
		"E20ds v4": azure_models.VirtualMachine{
			Name:              "E20ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.8768,
		},
		"E32ds v4": azure_models.VirtualMachine{
			Name:              "E32ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.8768,
		},
		"E48ds v4": azure_models.VirtualMachine{
			Name:              "E48ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.8768,
		},
		"E64ds v4": azure_models.VirtualMachine{
			Name:              "E64ds v4",
			Series:            "E2ds – E64ds v4",
			VCPUs:             64,
			Memory:            504,
			EmbodiedEmissions: 1.8768,
		},
		"E80ids v4 1": azure_models.VirtualMachine{
			Name:              "E80ids v4 1",
			Series:            "E2ds – E64ds v4",
			VCPUs:             80,
			Memory:            504,
			EmbodiedEmissions: 1.8768,
		},
		// E2 – E64 v4
		"E2 v4": azure_models.VirtualMachine{
			Name:              "E2 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.0098,
		},
		"E4 v4": azure_models.VirtualMachine{
			Name:              "E4 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.0098,
		},
		"E8 v4": azure_models.VirtualMachine{
			Name:              "E8 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0098,
		},
		"E16 v4": azure_models.VirtualMachine{
			Name:              "E16 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0098,
		},
		"E32 v4": azure_models.VirtualMachine{
			Name:              "E32 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0098,
		},
		"E48 v4": azure_models.VirtualMachine{
			Name:              "E48 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0098,
		},
		"E64 v4": azure_models.VirtualMachine{
			Name:              "E64 v4",
			Series:            "E2 – E64 v4",
			VCPUs:             64,
			Memory:            504,
			EmbodiedEmissions: 2.0098,
		},
		// E2s – E64s v4
		"E2s v4": azure_models.VirtualMachine{
			Name:              "E2s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.7768,
		},
		"E4s v4": azure_models.VirtualMachine{
			Name:              "E4s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.7768,
		},
		"E8s v4": azure_models.VirtualMachine{
			Name:              "E8s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.7768,
		},
		"E16s v4": azure_models.VirtualMachine{
			Name:              "E16s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.7768,
		},
		"E20s v4": azure_models.VirtualMachine{
			Name:              "E20s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.7768,
		},
		"E32s v4": azure_models.VirtualMachine{
			Name:              "E32s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.7768,
		},
		"E48s v4": azure_models.VirtualMachine{
			Name:              "E48s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.7768,
		},
		"E64s v4": azure_models.VirtualMachine{
			Name:              "E64s v4",
			Series:            "E2s – E64s v4",
			VCPUs:             64,
			Memory:            504,
			EmbodiedEmissions: 1.7768,
		},
		"E80is v4 1": azure_models.VirtualMachine{
			Name:              "E80is v4 1",
			Series:            "E2s – E64s v4",
			VCPUs:             80,
			Memory:            504,
			EmbodiedEmissions: 1.8268,
		},
		// E2-64 v3
		"E2 v3": azure_models.VirtualMachine{
			Name:              "E2 v3",
			Series:            "E2-64 v3",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.727,
		},
		"E4 v3": azure_models.VirtualMachine{
			Name:              "E4 v3",
			Series:            "E2-64 v3",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.727,
		},
		"E8 v3": azure_models.VirtualMachine{
			Name:              "E8 v3",
			Series:            "E2-64 v3",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.727,
		},
		"E16 v3": azure_models.VirtualMachine{
			Name:              "E16 v3",
			Series:            "E2-64 v3",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.9155,
		},
		"E20 v3": azure_models.VirtualMachine{
			Name:              "E20 v3",
			Series:            "E2-64 v3",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.727,
		},
		"E32 v3": azure_models.VirtualMachine{
			Name:              "E32 v3",
			Series:            "E2-64 v3",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.727,
		},
		"E48 v3": azure_models.VirtualMachine{
			Name:              "E48 v3",
			Series:            "E2-64 v3",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.727,
		},
		"E64i v3 1": azure_models.VirtualMachine{
			Name:              "E64i v3 1",
			Series:            "E2-64 v3",
			VCPUs:             64,
			Memory:            432,
			EmbodiedEmissions: 1.727,
		},
		"E64 v3": azure_models.VirtualMachine{
			Name:              "E64 v3",
			Series:            "E2-64 v3",
			VCPUs:             64,
			Memory:            432,
			EmbodiedEmissions: 1.727,
		},
		// E2s-64s v3
		"E2s v3": azure_models.VirtualMachine{
			Name:              "E2s v3",
			Series:            "E2s-64s v3",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.777,
		},
		"E4s v3": azure_models.VirtualMachine{
			Name:              "E4s v3",
			Series:            "E2s-64s v3",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.777,
		},
		"E8s v3": azure_models.VirtualMachine{
			Name:              "E8s v3",
			Series:            "E2s-64s v3",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.777,
		},
		"E16s v3": azure_models.VirtualMachine{
			Name:              "E16s v3",
			Series:            "E2s-64s v3",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.7935,
		},
		"E20s v3": azure_models.VirtualMachine{
			Name:              "E20s v3",
			Series:            "E2s-64s v3",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.777,
		},
		"E32s v3": azure_models.VirtualMachine{
			Name:              "E32s v3",
			Series:            "E2s-64s v3",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.777,
		},
		"E48s v3": azure_models.VirtualMachine{
			Name:              "E48s v3",
			Series:            "E2s-64s v3",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.777,
		},
		"E64is v3 1": azure_models.VirtualMachine{
			Name:              "E64is v3 1",
			Series:            "E2s-64s v3",
			VCPUs:             64,
			Memory:            432,
			EmbodiedEmissions: 1.777,
		},
		"E64s v3": azure_models.VirtualMachine{
			Name:              "E64s v3",
			Series:            "E2s-64s v3",
			VCPUs:             64,
			Memory:            432,
			EmbodiedEmissions: 1.777,
		},
		// D11-15 v2
		"D11 v2": azure_models.VirtualMachine{
			Name:              "D11 v2",
			Series:            "D11-15 v2",
			VCPUs:             2,
			Memory:            14,
			EmbodiedEmissions: 1.2346,
		},
		"D12 v2": azure_models.VirtualMachine{
			Name:              "D12 v2",
			Series:            "D11-15 v2",
			VCPUs:             4,
			Memory:            28,
			EmbodiedEmissions: 1.322,
		},
		"D13 v2": azure_models.VirtualMachine{
			Name:              "D13 v2",
			Series:            "D11-15 v2",
			VCPUs:             8,
			Memory:            56,
			EmbodiedEmissions: 1.322,
		},
		"D14 v2": azure_models.VirtualMachine{
			Name:              "D14 v2",
			Series:            "D11-15 v2",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.322,
		},
		"D15i v2 1": azure_models.VirtualMachine{
			Name:              "D15i v2 1",
			Series:            "D11-15 v2",
			VCPUs:             20,
			Memory:            140,
			EmbodiedEmissions: 1.322,
		},
		"D15 v2": azure_models.VirtualMachine{
			Name:              "D15 v2",
			Series:            "D11-15 v2",
			VCPUs:             20,
			Memory:            140,
			EmbodiedEmissions: 1.322,
		},
		// D11S-15S v2
		"Ds11 v2": azure_models.VirtualMachine{
			Name:              "Ds11 v2",
			Series:            "D11S-15S v2",
			VCPUs:             2,
			Memory:            14,
			EmbodiedEmissions: 1.322,
		},
		"Ds12 v2": azure_models.VirtualMachine{
			Name:              "Ds12 v2",
			Series:            "D11S-15S v2",
			VCPUs:             4,
			Memory:            28,
			EmbodiedEmissions: 1.322,
		},
		"Ds13 v2": azure_models.VirtualMachine{
			Name:              "Ds13 v2",
			Series:            "D11S-15S v2",
			VCPUs:             8,
			Memory:            56,
			EmbodiedEmissions: 1.322,
		},
		"Ds14 v2": azure_models.VirtualMachine{
			Name:              "Ds14 v2",
			Series:            "D11S-15S v2",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.322,
		},
		"Ds15i v2 1": azure_models.VirtualMachine{
			Name:              "Ds15i v2 1",
			Series:            "D11S-15S v2",
			VCPUs:             20,
			Memory:            140,
			EmbodiedEmissions: 1.322,
		},
		"Ds15 v2": azure_models.VirtualMachine{
			Name:              "Ds15 v2",
			Series:            "D11S-15S v2",
			VCPUs:             20,
			Memory:            140,
			EmbodiedEmissions: 1.322,
		},
		// G-series
		"G1": azure_models.VirtualMachine{
			Name:              "G1",
			Series:            "G-series",
			VCPUs:             2,
			Memory:            28,
			EmbodiedEmissions: 1.7491,
		},
		"G2": azure_models.VirtualMachine{
			Name:              "G2",
			Series:            "G-series",
			VCPUs:             4,
			Memory:            56,
			EmbodiedEmissions: 1.7491,
		},
		"G3": azure_models.VirtualMachine{
			Name:              "G3",
			Series:            "G-series",
			VCPUs:             8,
			Memory:            112,
			EmbodiedEmissions: 1.7491,
		},
		"G4": azure_models.VirtualMachine{
			Name:              "G4",
			Series:            "G-series",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.7491,
		},
		"G5": azure_models.VirtualMachine{
			Name:              "G5",
			Series:            "G-series",
			VCPUs:             32,
			Memory:            448,
			EmbodiedEmissions: 1.7491,
		},
		// Gs-Series
		"Gs1": azure_models.VirtualMachine{
			Name:              "Gs1",
			Series:            "Gs-Series",
			VCPUs:             2,
			Memory:            28,
			EmbodiedEmissions: 1.7491,
		},
		"Gs2": azure_models.VirtualMachine{
			Name:              "Gs2",
			Series:            "Gs-Series",
			VCPUs:             4,
			Memory:            56,
			EmbodiedEmissions: 1.7491,
		},
		"Gs3": azure_models.VirtualMachine{
			Name:              "Gs3",
			Series:            "Gs-Series",
			VCPUs:             8,
			Memory:            112,
			EmbodiedEmissions: 1.7491,
		},
		"Gs4": azure_models.VirtualMachine{
			Name:              "Gs4",
			Series:            "Gs-Series",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.7491,
		},
		"Gs5": azure_models.VirtualMachine{
			Name:              "Gs5",
			Series:            "Gs-Series",
			VCPUs:             32,
			Memory:            448,
			EmbodiedEmissions: 1.7491,
		},
		// M-series
		"M8ms": azure_models.VirtualMachine{
			Name:              "M8ms",
			Series:            "M-series",
			VCPUs:             8,
			Memory:            219,
			EmbodiedEmissions: 6.8086,
		},
		"M16ms": azure_models.VirtualMachine{
			Name:              "M16ms",
			Series:            "M-series",
			VCPUs:             16,
			Memory:            438,
			EmbodiedEmissions: 6.5256,
		},
		"M32ts": azure_models.VirtualMachine{
			Name:              "M32ts",
			Series:            "M-series",
			VCPUs:             32,
			Memory:            192,
			EmbodiedEmissions: 6.5256,
		},
		"M32ls": azure_models.VirtualMachine{
			Name:              "M32ls",
			Series:            "M-series",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 6.5256,
		},
		"M32ms": azure_models.VirtualMachine{
			Name:              "M32ms",
			Series:            "M-series",
			VCPUs:             32,
			Memory:            875,
			EmbodiedEmissions: 6.5256,
		},
		"M64ls": azure_models.VirtualMachine{
			Name:              "M64ls",
			Series:            "M-series",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 6.5256,
		},
		"M64s": azure_models.VirtualMachine{
			Name:              "M64s",
			Series:            "M-series",
			VCPUs:             64,
			Memory:            1024,
			EmbodiedEmissions: 6.5256,
		},
		"M64 1": azure_models.VirtualMachine{
			Name:              "M64 1",
			Series:            "M-series",
			VCPUs:             64,
			Memory:            1024,
			EmbodiedEmissions: 6.5256,
		},
		"M64ms": azure_models.VirtualMachine{
			Name:              "M64ms",
			Series:            "M-series",
			VCPUs:             64,
			Memory:            1792,
			EmbodiedEmissions: 6.5256,
		},
		"M64m 1": azure_models.VirtualMachine{
			Name:              "M64m 1",
			Series:            "M-series",
			VCPUs:             64,
			Memory:            1792,
			EmbodiedEmissions: 6.5256,
		},
		"M128s": azure_models.VirtualMachine{
			Name:              "M128s",
			Series:            "M-series",
			VCPUs:             128,
			Memory:            2048,
			EmbodiedEmissions: 6.5256,
		},
		"M128 1": azure_models.VirtualMachine{
			Name:              "M128 1",
			Series:            "M-series",
			VCPUs:             128,
			Memory:            2048,
			EmbodiedEmissions: 4.2705,
		},
		"M128ms": azure_models.VirtualMachine{
			Name:              "M128ms",
			Series:            "M-series",
			VCPUs:             128,
			Memory:            3892,
			EmbodiedEmissions: 6.5256,
		},
		"M128m 1": azure_models.VirtualMachine{
			Name:              "M128m 1",
			Series:            "M-series",
			VCPUs:             128,
			Memory:            3892,
			EmbodiedEmissions: 6.5256,
		},
		// Mdsv2-series
		"M32dms v2": azure_models.VirtualMachine{
			Name:              "M32dms v2",
			Series:            "Mdsv2-series",
			VCPUs:             32,
			Memory:            875,
			EmbodiedEmissions: 6.8086,
		},
		"M64ds v2": azure_models.VirtualMachine{
			Name:              "M64ds v2",
			Series:            "Mdsv2-series",
			VCPUs:             64,
			Memory:            1024,
			EmbodiedEmissions: 6.8086,
		},
		"M64dms v2": azure_models.VirtualMachine{
			Name:              "M64dms v2",
			Series:            "Mdsv2-series",
			VCPUs:             64,
			Memory:            1792,
			EmbodiedEmissions: 6.8086,
		},
		"M128ds v2": azure_models.VirtualMachine{
			Name:              "M128ds v2",
			Series:            "Mdsv2-series",
			VCPUs:             128,
			Memory:            2048,
			EmbodiedEmissions: 6.8086,
		},
		"M128dms v2": azure_models.VirtualMachine{
			Name:              "M128dms v2",
			Series:            "Mdsv2-series",
			VCPUs:             128,
			Memory:            3892,
			EmbodiedEmissions: 6.8086,
		},
		"M192ids v2": azure_models.VirtualMachine{
			Name:              "M192ids v2",
			Series:            "Mdsv2-series",
			VCPUs:             192,
			Memory:            2048,
			EmbodiedEmissions: 6.8086,
		},
		"M192idms v2": azure_models.VirtualMachine{
			Name:              "M192idms v2",
			Series:            "Mdsv2-series",
			VCPUs:             192,
			Memory:            4096,
			EmbodiedEmissions: 6.8086,
		},
		// Msv2-series
		"M32ms v2": azure_models.VirtualMachine{
			Name:              "M32ms v2",
			Series:            "Msv2-series",
			VCPUs:             32,
			Memory:            875,
			EmbodiedEmissions: 6.7586,
		},
		"M64s v2": azure_models.VirtualMachine{
			Name:              "M64s v2",
			Series:            "Msv2-series",
			VCPUs:             64,
			Memory:            1024,
			EmbodiedEmissions: 16.8885,
		},
		"M64ms v2": azure_models.VirtualMachine{
			Name:              "M64ms v2",
			Series:            "Msv2-series",
			VCPUs:             64,
			Memory:            1792,
			EmbodiedEmissions: 6.7586,
		},
		"M128s v2": azure_models.VirtualMachine{
			Name:              "M128s v2",
			Series:            "Msv2-series",
			VCPUs:             128,
			Memory:            2048,
			EmbodiedEmissions: 6.7586,
		},
		"M128ms v2": azure_models.VirtualMachine{
			Name:              "M128ms v2",
			Series:            "Msv2-series",
			VCPUs:             128,
			Memory:            3892,
			EmbodiedEmissions: 6.7586,
		},
		"M192is v2": azure_models.VirtualMachine{
			Name:              "M192is v2",
			Series:            "Msv2-series",
			VCPUs:             192,
			Memory:            2048,
			EmbodiedEmissions: 6.7586,
		},
		"M192ims v2": azure_models.VirtualMachine{
			Name:              "M192ims v2",
			Series:            "Msv2-series",
			VCPUs:             192,
			Memory:            4096,
			EmbodiedEmissions: 6.7586,
		},
		// Mv2-series
		"M208s v2": azure_models.VirtualMachine{
			Name:              "M208s v2",
			Series:            "Mv2-series",
			VCPUs:             208,
			Memory:            2850,
			EmbodiedEmissions: 16.9385,
		},
		"M208ms v2": azure_models.VirtualMachine{
			Name:              "M208ms v2",
			Series:            "Mv2-series",
			VCPUs:             208,
			Memory:            5700,
			EmbodiedEmissions: 16.9385,
		},
		"M416s v2": azure_models.VirtualMachine{
			Name:              "M416s v2",
			Series:            "Mv2-series",
			VCPUs:             416,
			Memory:            5700,
			EmbodiedEmissions: 16.9385,
		},
		"M416ms v2": azure_models.VirtualMachine{
			Name:              "M416ms v2",
			Series:            "Mv2-series",
			VCPUs:             416,
			Memory:            11400,
			EmbodiedEmissions: 16.9385,
		},
		// SAP HANA on Azure Large Instances
		"S96": azure_models.VirtualMachine{
			Name:              "S96",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             96,
			Memory:            768,
			EmbodiedEmissions: 17.7706,
		},
		"S192": azure_models.VirtualMachine{
			Name:              "S192",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             192,
			Memory:            2048,
			EmbodiedEmissions: 17.7706,
		},
		"S192m": azure_models.VirtualMachine{
			Name:              "S192m",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             192,
			Memory:            4096,
			EmbodiedEmissions: 17.7706,
		},
		"S192xm": azure_models.VirtualMachine{
			Name:              "S192xm",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             192,
			Memory:            6144,
			EmbodiedEmissions: 17.7706,
		},
		"S384": azure_models.VirtualMachine{
			Name:              "S384",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             384,
			Memory:            4096,
			EmbodiedEmissions: 17.7706,
		},
		"S384m": azure_models.VirtualMachine{
			Name:              "S384m",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             384,
			Memory:            6144,
			EmbodiedEmissions: 17.7706,
		},
		"S384xm": azure_models.VirtualMachine{
			Name:              "S384xm",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             384,
			Memory:            8192,
			EmbodiedEmissions: 17.7706,
		},
		"S384xxm": azure_models.VirtualMachine{
			Name:              "S384xxm",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             384,
			Memory:            12000,
			EmbodiedEmissions: 17.7706,
		},
		"S576m": azure_models.VirtualMachine{
			Name:              "S576m",
			Series:            "SAP HANA on Azure Large Instances",
			VCPUs:             576,
			Memory:            12000,
			EmbodiedEmissions: 17.7706,
		},
		// SAP HANA on Azure Large Instances (second generation)
		"S224": azure_models.VirtualMachine{
			Name:              "S224",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            3072,
			EmbodiedEmissions: 52.2545,
		},
		"S224oo": azure_models.VirtualMachine{
			Name:              "S224oo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            4608,
			EmbodiedEmissions: 52.2545,
		},
		"S224m": azure_models.VirtualMachine{
			Name:              "S224m",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            6144,
			EmbodiedEmissions: 52.2545,
		},
		"S224om": azure_models.VirtualMachine{
			Name:              "S224om",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            6144,
			EmbodiedEmissions: 52.2545,
		},
		"S224ooo": azure_models.VirtualMachine{
			Name:              "S224ooo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            7680,
			EmbodiedEmissions: 52.2545,
		},
		"S224oom": azure_models.VirtualMachine{
			Name:              "S224oom",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             224,
			Memory:            9216,
			EmbodiedEmissions: 52.2545,
		},
		"S448": azure_models.VirtualMachine{
			Name:              "S448",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            6144,
			EmbodiedEmissions: 52.2545,
		},
		"S448oo": azure_models.VirtualMachine{
			Name:              "S448oo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            9216,
			EmbodiedEmissions: 52.2545,
		},
		"S448m": azure_models.VirtualMachine{
			Name:              "S448m",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            12288,
			EmbodiedEmissions: 52.2545,
		},
		"S448om": azure_models.VirtualMachine{
			Name:              "S448om",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            12288,
			EmbodiedEmissions: 52.2545,
		},
		"S448ooo": azure_models.VirtualMachine{
			Name:              "S448ooo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            15360,
			EmbodiedEmissions: 52.2545,
		},
		"S448oom": azure_models.VirtualMachine{
			Name:              "S448oom",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             448,
			Memory:            18432,
			EmbodiedEmissions: 52.2545,
		},
		"S672": azure_models.VirtualMachine{
			Name:              "S672",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            9216,
			EmbodiedEmissions: 52.2545,
		},
		"S672oo": azure_models.VirtualMachine{
			Name:              "S672oo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            13824,
			EmbodiedEmissions: 52.2545,
		},
		"S672m": azure_models.VirtualMachine{
			Name:              "S672m",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            18432,
			EmbodiedEmissions: 52.2545,
		},
		"S672om": azure_models.VirtualMachine{
			Name:              "S672om",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            18432,
			EmbodiedEmissions: 52.2545,
		},
		"S672ooo": azure_models.VirtualMachine{
			Name:              "S672ooo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            23040,
			EmbodiedEmissions: 52.2545,
		},
		"S672oom": azure_models.VirtualMachine{
			Name:              "S672oom",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             672,
			Memory:            27648,
			EmbodiedEmissions: 52.2545,
		},
		"S896": azure_models.VirtualMachine{
			Name:              "S896",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            12288,
			EmbodiedEmissions: 52.2545,
		},
		"S896oo": azure_models.VirtualMachine{
			Name:              "S896oo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            18432,
			EmbodiedEmissions: 52.2545,
		},
		"S896m": azure_models.VirtualMachine{
			Name:              "S896m",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            24576,
			EmbodiedEmissions: 52.2545,
		},
		"S896om": azure_models.VirtualMachine{
			Name:              "S896om",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            24576,
			EmbodiedEmissions: 52.2545,
		},
		"S896ooo": azure_models.VirtualMachine{
			Name:              "S896ooo",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            30720,
			EmbodiedEmissions: 52.2545,
		},
		"S896oom": azure_models.VirtualMachine{
			Name:              "S896oom",
			Series:            "SAP HANA on Azure Large Instances (second generation)",
			VCPUs:             896,
			Memory:            36864,
			EmbodiedEmissions: 52.2545,
		},
		// Lsv2-series
		"L8s v2": azure_models.VirtualMachine{
			Name:              "L8s v2",
			Series:            "Lsv2-series",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0154,
		},
		"L16s v2": azure_models.VirtualMachine{
			Name:              "L16s v2",
			Series:            "Lsv2-series",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0154,
		},
		"L32s v2": azure_models.VirtualMachine{
			Name:              "L32s v2",
			Series:            "Lsv2-series",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0154,
		},
		"L48s v2": azure_models.VirtualMachine{
			Name:              "L48s v2",
			Series:            "Lsv2-series",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0154,
		},
		"L64s v2": azure_models.VirtualMachine{
			Name:              "L64s v2",
			Series:            "Lsv2-series",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.0154,
		},
		"L80s v2": azure_models.VirtualMachine{
			Name:              "L80s v2",
			Series:            "Lsv2-series",
			VCPUs:             80,
			Memory:            640,
			EmbodiedEmissions: 2.0154,
		},
		// Ls-series
		"L4s": azure_models.VirtualMachine{
			Name:              "L4s",
			Series:            "Ls-series",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.5329,
		},
		"L8s": azure_models.VirtualMachine{
			Name:              "L8s",
			Series:            "Ls-series",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.5329,
		},
		"L16s": azure_models.VirtualMachine{
			Name:              "L16s",
			Series:            "Ls-series",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.5329,
		},
		"L32s": azure_models.VirtualMachine{
			Name:              "L32s",
			Series:            "Ls-series",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.5329,
		},
		// NC-series
		"NC6": azure_models.VirtualMachine{
			Name:              "NC6",
			Series:            "NC-series",
			VCPUs:             6,
			Memory:            56,
			EmbodiedEmissions: 2.0385,
		},
		"NC12": azure_models.VirtualMachine{
			Name:              "NC12",
			Series:            "NC-series",
			VCPUs:             12,
			Memory:            112,
			EmbodiedEmissions: 2.0385,
		},
		"NC24r": azure_models.VirtualMachine{
			Name:              "NC24r",
			Series:            "NC-series",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.0385,
		},
		"NC24": azure_models.VirtualMachine{
			Name:              "NC24",
			Series:            "NC-series",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.0385,
		},
		// NC-series Promo
		"NC6 Promo": azure_models.VirtualMachine{
			Name:              "NC6 Promo",
			Series:            "NC-series Promo",
			VCPUs:             6,
			Memory:            56,
			EmbodiedEmissions: 2.0385,
		},
		"NC12 Promo": azure_models.VirtualMachine{
			Name:              "NC12 Promo",
			Series:            "NC-series Promo",
			VCPUs:             12,
			Memory:            112,
			EmbodiedEmissions: 2.0385,
		},
		"NC24 Promo": azure_models.VirtualMachine{
			Name:              "NC24 Promo",
			Series:            "NC-series Promo",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.0385,
		},
		"NC24r Promo": azure_models.VirtualMachine{
			Name:              "NC24r Promo",
			Series:            "NC-series Promo",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.0385,
		},
		// NCsv2-series
		"NC6s v2": azure_models.VirtualMachine{
			Name:              "NC6s v2",
			Series:            "NCsv2-series",
			VCPUs:             6,
			Memory:            112,
			EmbodiedEmissions: 2.3491,
		},
		"NC12s v2": azure_models.VirtualMachine{
			Name:              "NC12s v2",
			Series:            "NCsv2-series",
			VCPUs:             12,
			Memory:            224,
			EmbodiedEmissions: 2.3491,
		},
		"NC24rs v2": azure_models.VirtualMachine{
			Name:              "NC24rs v2",
			Series:            "NCsv2-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		"NC24s v2": azure_models.VirtualMachine{
			Name:              "NC24s v2",
			Series:            "NCsv2-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		// NCsv3-series
		"NC6s v3": azure_models.VirtualMachine{
			Name:              "NC6s v3",
			Series:            "NCsv3-series",
			VCPUs:             6,
			Memory:            112,
			EmbodiedEmissions: 2.3491,
		},
		"NC12s v3": azure_models.VirtualMachine{
			Name:              "NC12s v3",
			Series:            "NCsv3-series",
			VCPUs:             12,
			Memory:            224,
			EmbodiedEmissions: 2.3491,
		},
		"NC24rs v3": azure_models.VirtualMachine{
			Name:              "NC24rs v3",
			Series:            "NCsv3-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		"NC24s v3": azure_models.VirtualMachine{
			Name:              "NC24s v3",
			Series:            "NCsv3-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		// NCas_T4_v3 Series
		"NC4as T4 v3": azure_models.VirtualMachine{
			Name:              "NC4as T4 v3",
			Series:            "NCas_T4_v3 Series",
			VCPUs:             4,
			Memory:            28,
			EmbodiedEmissions: 2.3491,
		},
		"NC8as T4 v3": azure_models.VirtualMachine{
			Name:              "NC8as T4 v3",
			Series:            "NCas_T4_v3 Series",
			VCPUs:             8,
			Memory:            56,
			EmbodiedEmissions: 2.3491,
		},
		"NC16as T4 v3": azure_models.VirtualMachine{
			Name:              "NC16as T4 v3",
			Series:            "NCas_T4_v3 Series",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 2.3491,
		},
		"NC64as T4 v3": azure_models.VirtualMachine{
			Name:              "NC64as T4 v3",
			Series:            "NCas_T4_v3 Series",
			VCPUs:             64,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		// NP-Series
		"NP10s": azure_models.VirtualMachine{
			Name:              "NP10s",
			Series:            "NP-Series",
			VCPUs:             10,
			Memory:            192,
			EmbodiedEmissions: 2.1929,
		},
		"NP20s": azure_models.VirtualMachine{
			Name:              "NP20s",
			Series:            "NP-Series",
			VCPUs:             20,
			Memory:            384,
			EmbodiedEmissions: 2.1929,
		},
		"NP40s": azure_models.VirtualMachine{
			Name:              "NP40s",
			Series:            "NP-Series",
			VCPUs:             40,
			Memory:            768,
			EmbodiedEmissions: 2.1929,
		},
		// NV-series
		"NV6": azure_models.VirtualMachine{
			Name:              "NV6",
			Series:            "NV-series",
			VCPUs:             6,
			Memory:            56,
			EmbodiedEmissions: 2.0385,
		},
		"NV12": azure_models.VirtualMachine{
			Name:              "NV12",
			Series:            "NV-series",
			VCPUs:             12,
			Memory:            112,
			EmbodiedEmissions: 2.0385,
		},
		"NV24": azure_models.VirtualMachine{
			Name:              "NV24",
			Series:            "NV-series",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.0385,
		},
		// NVv3-series
		"NV12s v3": azure_models.VirtualMachine{
			Name:              "NV12s v3",
			Series:            "NVv3-series",
			VCPUs:             12,
			Memory:            112,
			EmbodiedEmissions: 2.3491,
		},
		"NV24s v3": azure_models.VirtualMachine{
			Name:              "NV24s v3",
			Series:            "NVv3-series",
			VCPUs:             24,
			Memory:            224,
			EmbodiedEmissions: 2.3491,
		},
		"NV48s v3": azure_models.VirtualMachine{
			Name:              "NV48s v3",
			Series:            "NVv3-series",
			VCPUs:             48,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		// NDs-series
		"ND6s": azure_models.VirtualMachine{
			Name:              "ND6s",
			Series:            "NDs-series",
			VCPUs:             6,
			Memory:            112,
			EmbodiedEmissions: 2.3491,
		},
		"ND12s": azure_models.VirtualMachine{
			Name:              "ND12s",
			Series:            "NDs-series",
			VCPUs:             12,
			Memory:            224,
			EmbodiedEmissions: 2.3491,
		},
		"ND24rs": azure_models.VirtualMachine{
			Name:              "ND24rs",
			Series:            "NDs-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		"ND24s": azure_models.VirtualMachine{
			Name:              "ND24s",
			Series:            "NDs-series",
			VCPUs:             24,
			Memory:            448,
			EmbodiedEmissions: 2.3491,
		},
		// NDv2 Series
		"ND40rs v2": azure_models.VirtualMachine{
			Name:              "ND40rs v2",
			Series:            "NDv2 Series",
			VCPUs:             40,
			Memory:            672,
			EmbodiedEmissions: 3.2598,
		},
		// ND A100 v4 series
		"ND96asr A100 v4": azure_models.VirtualMachine{
			Name:              "ND96asr A100 v4",
			Series:            "ND A100 v4 series",
			VCPUs:             96,
			Memory:            900,
			EmbodiedEmissions: 3.576,
		},
		// NDm A100 v4 series
		"ND96amsr A100 v4": azure_models.VirtualMachine{
			Name:              "ND96amsr A100 v4",
			Series:            "NDm A100 v4 series",
			VCPUs:             96,
			Memory:            1900,
			EmbodiedEmissions: 4.9629,
		},
		// H-series
		"H8": azure_models.VirtualMachine{
			Name:              "H8",
			Series:            "H-series",
			VCPUs:             8,
			Memory:            56,
			EmbodiedEmissions: 1.4385,
		},
		"H8m": azure_models.VirtualMachine{
			Name:              "H8m",
			Series:            "H-series",
			VCPUs:             8,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16r": azure_models.VirtualMachine{
			Name:              "H16r",
			Series:            "H-series",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16": azure_models.VirtualMachine{
			Name:              "H16",
			Series:            "H-series",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16mr": azure_models.VirtualMachine{
			Name:              "H16mr",
			Series:            "H-series",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.4385,
		},
		"H16m": azure_models.VirtualMachine{
			Name:              "H16m",
			Series:            "H-series",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.4385,
		},
		// H-series promo
		"H8 Promo": azure_models.VirtualMachine{
			Name:              "H8 Promo",
			Series:            "H-series promo",
			VCPUs:             8,
			Memory:            56,
			EmbodiedEmissions: 1.4385,
		},
		"H8m Promo": azure_models.VirtualMachine{
			Name:              "H8m Promo",
			Series:            "H-series promo",
			VCPUs:             8,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16 Promo": azure_models.VirtualMachine{
			Name:              "H16 Promo",
			Series:            "H-series promo",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16r Promo": azure_models.VirtualMachine{
			Name:              "H16r Promo",
			Series:            "H-series promo",
			VCPUs:             16,
			Memory:            112,
			EmbodiedEmissions: 1.4385,
		},
		"H16m Promo": azure_models.VirtualMachine{
			Name:              "H16m Promo",
			Series:            "H-series promo",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.4385,
		},
		"H16mr Promo": azure_models.VirtualMachine{
			Name:              "H16mr Promo",
			Series:            "H-series promo",
			VCPUs:             16,
			Memory:            224,
			EmbodiedEmissions: 1.4385,
		},
		// HBv2-series
		"HB120rs v2": azure_models.VirtualMachine{
			Name:              "HB120rs v2",
			Series:            "HBv2-series",
			VCPUs:             120,
			Memory:            480,
			EmbodiedEmissions: 1.6935,
		},
		// HBv3-series
		"HB120rs v3": azure_models.VirtualMachine{
			Name:              "HB120rs v3",
			Series:            "HBv3-series",
			VCPUs:             120,
			Memory:            448,
			EmbodiedEmissions: 1.6991,
		},
		// HC-series
		"HC44rs": azure_models.VirtualMachine{
			Name:              "HC44rs",
			Series:            "HC-series",
			VCPUs:             44,
			Memory:            352,
			EmbodiedEmissions: 1.616,
		},
		// HB-series
		"HB60rs": azure_models.VirtualMachine{
			Name:              "HB60rs",
			Series:            "HB-series",
			VCPUs:             60,
			Memory:            224,
			EmbodiedEmissions: 1.444,
		},
		// D2as – D96as v5
		"D2as v5": azure_models.VirtualMachine{
			Name:              "D2as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5104,
		},
		"D4as v5": azure_models.VirtualMachine{
			Name:              "D4as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5104,
		},
		"D8as v5": azure_models.VirtualMachine{
			Name:              "D8as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5104,
		},
		"D16as v5": azure_models.VirtualMachine{
			Name:              "D16as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5104,
		},
		"D32as v5": azure_models.VirtualMachine{
			Name:              "D32as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5104,
		},
		"D48as v5": azure_models.VirtualMachine{
			Name:              "D48as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5104,
		},
		"D64as v5": azure_models.VirtualMachine{
			Name:              "D64as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5104,
		},
		"D96as v5": azure_models.VirtualMachine{
			Name:              "D96as v5",
			Series:            "D2as – D96as v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.5104,
		},
		// D2ads – D96ads v5
		"D2ads v5": azure_models.VirtualMachine{
			Name:              "D2ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.6104,
		},
		"D4ads v5": azure_models.VirtualMachine{
			Name:              "D4ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.6104,
		},
		"D8ads v5": azure_models.VirtualMachine{
			Name:              "D8ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.6104,
		},
		"D16ads v5": azure_models.VirtualMachine{
			Name:              "D16ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.6104,
		},
		"D32ads v5": azure_models.VirtualMachine{
			Name:              "D32ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.6104,
		},
		"D48ads v5": azure_models.VirtualMachine{
			Name:              "D48ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.6104,
		},
		"D64ads v5": azure_models.VirtualMachine{
			Name:              "D64ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.6104,
		},
		"D96ads v5": azure_models.VirtualMachine{
			Name:              "D96ads v5",
			Series:            "D2ads – D96ads v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.6104,
		},
		// D2d – D96d v5
		"D2d v5": azure_models.VirtualMachine{
			Name:              "D2d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.6104,
		},
		"D4d v5": azure_models.VirtualMachine{
			Name:              "D4d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.6104,
		},
		"D8d v5": azure_models.VirtualMachine{
			Name:              "D8d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.6104,
		},
		"D16d v5": azure_models.VirtualMachine{
			Name:              "D16d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.6104,
		},
		"D32d v5": azure_models.VirtualMachine{
			Name:              "D32d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.6104,
		},
		"D48d v5": azure_models.VirtualMachine{
			Name:              "D48d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.6104,
		},
		"D64d v5": azure_models.VirtualMachine{
			Name:              "D64d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.6104,
		},
		"D96d v5": azure_models.VirtualMachine{
			Name:              "D96d v5",
			Series:            "D2d – D96d v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.6104,
		},
		// D2ds – D96ds v5
		"D2ds v5": azure_models.VirtualMachine{
			Name:              "D2ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.6104,
		},
		"D4ds v5": azure_models.VirtualMachine{
			Name:              "D4ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.6104,
		},
		"D8ds v5": azure_models.VirtualMachine{
			Name:              "D8ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.6104,
		},
		"D16ds v5": azure_models.VirtualMachine{
			Name:              "D16ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.6104,
		},
		"D32ds v5": azure_models.VirtualMachine{
			Name:              "D32ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.6104,
		},
		"D48ds v5": azure_models.VirtualMachine{
			Name:              "D48ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.6104,
		},
		"D64ds v5": azure_models.VirtualMachine{
			Name:              "D64ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.6104,
		},
		"D96ds v5": azure_models.VirtualMachine{
			Name:              "D96ds v5",
			Series:            "D2ds – D96ds v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.6104,
		},
		// D2 – D96 v5
		"D2 v5": azure_models.VirtualMachine{
			Name:              "D2 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5104,
		},
		"D4 v5": azure_models.VirtualMachine{
			Name:              "D4 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5104,
		},
		"D8 v5": azure_models.VirtualMachine{
			Name:              "D8 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5104,
		},
		"D16 v5": azure_models.VirtualMachine{
			Name:              "D16 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5104,
		},
		"D32 v5": azure_models.VirtualMachine{
			Name:              "D32 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5104,
		},
		"D48 v5": azure_models.VirtualMachine{
			Name:              "D48 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5104,
		},
		"D64 v5": azure_models.VirtualMachine{
			Name:              "D64 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5104,
		},
		"D96 v5": azure_models.VirtualMachine{
			Name:              "D96 v5",
			Series:            "D2 – D96 v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.5104,
		},
		// D2s – D96s v5
		"D2s v5": azure_models.VirtualMachine{
			Name:              "D2s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             2,
			Memory:            8,
			EmbodiedEmissions: 1.5104,
		},
		"D4s v5": azure_models.VirtualMachine{
			Name:              "D4s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             4,
			Memory:            16,
			EmbodiedEmissions: 1.5104,
		},
		"D8s v5": azure_models.VirtualMachine{
			Name:              "D8s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             8,
			Memory:            32,
			EmbodiedEmissions: 1.5104,
		},
		"D16s v5": azure_models.VirtualMachine{
			Name:              "D16s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             16,
			Memory:            64,
			EmbodiedEmissions: 1.5104,
		},
		"D32s v5": azure_models.VirtualMachine{
			Name:              "D32s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             32,
			Memory:            128,
			EmbodiedEmissions: 1.5104,
		},
		"D48s v5": azure_models.VirtualMachine{
			Name:              "D48s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             48,
			Memory:            192,
			EmbodiedEmissions: 1.5104,
		},
		"D64s v5": azure_models.VirtualMachine{
			Name:              "D64s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             64,
			Memory:            256,
			EmbodiedEmissions: 1.5104,
		},
		"D96s v5": azure_models.VirtualMachine{
			Name:              "D96s v5",
			Series:            "D2s – D96s v5",
			VCPUs:             96,
			Memory:            384,
			EmbodiedEmissions: 1.5104,
		},
		// FX-series
		"FX4mds": azure_models.VirtualMachine{
			Name:              "FX4mds",
			Series:            "FX-series",
			VCPUs:             4,
			Memory:            84,
			EmbodiedEmissions: 1.2,
		},
		"FX12mds": azure_models.VirtualMachine{
			Name:              "FX12mds",
			Series:            "FX-series",
			VCPUs:             12,
			Memory:            252,
			EmbodiedEmissions: 1.2,
		},
		"FX24mds": azure_models.VirtualMachine{
			Name:              "FX24mds",
			Series:            "FX-series",
			VCPUs:             24,
			Memory:            504,
			EmbodiedEmissions: 1.2,
		},
		"FX36mds": azure_models.VirtualMachine{
			Name:              "FX36mds",
			Series:            "FX-series",
			VCPUs:             36,
			Memory:            756,
			EmbodiedEmissions: 1.2,
		},
		"FX48mds": azure_models.VirtualMachine{
			Name:              "FX48mds",
			Series:            "FX-series",
			VCPUs:             48,
			Memory:            1008,
			EmbodiedEmissions: 1.2,
		},
		// E2as – E96as v5
		"E2as v5": azure_models.VirtualMachine{
			Name:              "E2as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.9098,
		},
		"E4as v5": azure_models.VirtualMachine{
			Name:              "E4as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.9098,
		},
		"E8as v5": azure_models.VirtualMachine{
			Name:              "E8as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.9098,
		},
		"E16as v5": azure_models.VirtualMachine{
			Name:              "E16as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.9098,
		},
		"E20as v5": azure_models.VirtualMachine{
			Name:              "E20as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.9098,
		},
		"E32as v5": azure_models.VirtualMachine{
			Name:              "E32as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.9098,
		},
		"E48as v5": azure_models.VirtualMachine{
			Name:              "E48as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.9098,
		},
		"E64as v5": azure_models.VirtualMachine{
			Name:              "E64as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 1.9098,
		},
		"E96as v5": azure_models.VirtualMachine{
			Name:              "E96as v5",
			Series:            "E2as – E96as v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 1.9098,
		},
		// E2ads – E96ads v5
		"E2ads v5": azure_models.VirtualMachine{
			Name:              "E2ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.0098,
		},
		"E4ads v5": azure_models.VirtualMachine{
			Name:              "E4ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.0098,
		},
		"E8ads v5": azure_models.VirtualMachine{
			Name:              "E8ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0098,
		},
		"E16ads v5": azure_models.VirtualMachine{
			Name:              "E16ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0098,
		},
		"E20ads v5": azure_models.VirtualMachine{
			Name:              "E20ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 2.0098,
		},
		"E32ads v5": azure_models.VirtualMachine{
			Name:              "E32ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0098,
		},
		"E48ads v5": azure_models.VirtualMachine{
			Name:              "E48ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0098,
		},
		"E64ads v5": azure_models.VirtualMachine{
			Name:              "E64ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.0098,
		},
		"E96ads v5": azure_models.VirtualMachine{
			Name:              "E96ads v5",
			Series:            "E2ads – E96ads v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		// E2d – E104d v5
		"E2d v5": azure_models.VirtualMachine{
			Name:              "E2d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.0098,
		},
		"E4d v5": azure_models.VirtualMachine{
			Name:              "E4d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.0098,
		},
		"E8d v5": azure_models.VirtualMachine{
			Name:              "E8d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0098,
		},
		"E16d v5": azure_models.VirtualMachine{
			Name:              "E16d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0098,
		},
		"E20d v5": azure_models.VirtualMachine{
			Name:              "E20d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 2.0098,
		},
		"E32d v5": azure_models.VirtualMachine{
			Name:              "E32d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0098,
		},
		"E48d v5": azure_models.VirtualMachine{
			Name:              "E48d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0098,
		},
		"E64d v5": azure_models.VirtualMachine{
			Name:              "E64d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.0098,
		},
		"E96d v5": azure_models.VirtualMachine{
			Name:              "E96d v5",
			Series:            "E2d – E104d v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		"E104id v5": azure_models.VirtualMachine{
			Name:              "E104id v5",
			Series:            "E2d – E104d v5",
			VCPUs:             104,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		// E2ds – E104ds v5
		"E2ds v5": azure_models.VirtualMachine{
			Name:              "E2ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.0098,
		},
		"E4ds v5": azure_models.VirtualMachine{
			Name:              "E4ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.0098,
		},
		"E8ds v5": azure_models.VirtualMachine{
			Name:              "E8ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.0098,
		},
		"E16ds v5": azure_models.VirtualMachine{
			Name:              "E16ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.0098,
		},
		"E20ds v5": azure_models.VirtualMachine{
			Name:              "E20ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 2.0098,
		},
		"E32ds v5": azure_models.VirtualMachine{
			Name:              "E32ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.0098,
		},
		"E48ds v5": azure_models.VirtualMachine{
			Name:              "E48ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.0098,
		},
		"E64ds v5": azure_models.VirtualMachine{
			Name:              "E64ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.0098,
		},
		"E96ds v5": azure_models.VirtualMachine{
			Name:              "E96ds v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		"E104ids v5": azure_models.VirtualMachine{
			Name:              "E104ids v5",
			Series:            "E2ds – E104ds v5",
			VCPUs:             104,
			Memory:            672,
			EmbodiedEmissions: 2.0098,
		},
		// E2 – E104 v5
		"E2 v5": azure_models.VirtualMachine{
			Name:              "E2 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.9098,
		},
		"E4 v5": azure_models.VirtualMachine{
			Name:              "E4 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.9098,
		},
		"E8 v5": azure_models.VirtualMachine{
			Name:              "E8 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.9098,
		},
		"E16 v5": azure_models.VirtualMachine{
			Name:              "E16 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.9098,
		},
		"E20 v5": azure_models.VirtualMachine{
			Name:              "E20 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.9098,
		},
		"E32 v5": azure_models.VirtualMachine{
			Name:              "E32 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.9098,
		},
		"E48 v5": azure_models.VirtualMachine{
			Name:              "E48 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.9098,
		},
		"E64 v5": azure_models.VirtualMachine{
			Name:              "E64 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 1.9098,
		},
		"E96 v5": azure_models.VirtualMachine{
			Name:              "E96 v5",
			Series:            "E2 – E104 v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 1.9098,
		},
		"E104i v5": azure_models.VirtualMachine{
			Name:              "E104i v5",
			Series:            "E2 – E104 v5",
			VCPUs:             104,
			Memory:            672,
			EmbodiedEmissions: 1.9098,
		},
		// E2s – E104s v5
		"E2s v5": azure_models.VirtualMachine{
			Name:              "E2s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.9098,
		},
		"E4s v5": azure_models.VirtualMachine{
			Name:              "E4s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.9098,
		},
		"E8s v5": azure_models.VirtualMachine{
			Name:              "E8s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.9098,
		},
		"E16s v5": azure_models.VirtualMachine{
			Name:              "E16s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.9098,
		},
		"E20s v5": azure_models.VirtualMachine{
			Name:              "E20s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             20,
			Memory:            160,
			EmbodiedEmissions: 1.9098,
		},
		"E32s v5": azure_models.VirtualMachine{
			Name:              "E32s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.9098,
		},
		"E48s v5": azure_models.VirtualMachine{
			Name:              "E48s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.9098,
		},
		"E64s v5": azure_models.VirtualMachine{
			Name:              "E64s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 1.9098,
		},
		"E96s v5": azure_models.VirtualMachine{
			Name:              "E96s v5",
			Series:            "E2s – E104s v5",
			VCPUs:             96,
			Memory:            672,
			EmbodiedEmissions: 1.9098,
		},
		"E104is v5": azure_models.VirtualMachine{
			Name:              "E104is v5",
			Series:            "E2s – E104s v5",
			VCPUs:             104,
			Memory:            672,
			EmbodiedEmissions: 1.9098,
		},
		// E2bds – E64bds v5
		"E2bds v5": azure_models.VirtualMachine{
			Name:              "E2bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 1.7879,
		},
		"E4bds v5": azure_models.VirtualMachine{
			Name:              "E4bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 1.7879,
		},
		"E8bds v5": azure_models.VirtualMachine{
			Name:              "E8bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 1.7879,
		},
		"E16bds v5": azure_models.VirtualMachine{
			Name:              "E16bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 1.7879,
		},
		"E32bds v5": azure_models.VirtualMachine{
			Name:              "E32bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 1.7879,
		},
		"E48bds v5": azure_models.VirtualMachine{
			Name:              "E48bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 1.7879,
		},
		"E64bds v5": azure_models.VirtualMachine{
			Name:              "E64bds v5",
			Series:            "E2bds – E64bds v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 1.7879,
		},
		// E2bs – E64bs v5
		"E2bs v5": azure_models.VirtualMachine{
			Name:              "E2bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             2,
			Memory:            16,
			EmbodiedEmissions: 2.1983,
		},
		"E4bs v5": azure_models.VirtualMachine{
			Name:              "E4bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             4,
			Memory:            32,
			EmbodiedEmissions: 2.1983,
		},
		"E8bs v5": azure_models.VirtualMachine{
			Name:              "E8bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             8,
			Memory:            64,
			EmbodiedEmissions: 2.1983,
		},
		"E16bs v5": azure_models.VirtualMachine{
			Name:              "E16bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             16,
			Memory:            128,
			EmbodiedEmissions: 2.1983,
		},
		"E32bs v5": azure_models.VirtualMachine{
			Name:              "E32bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             32,
			Memory:            256,
			EmbodiedEmissions: 2.1983,
		},
		"E48bs v5": azure_models.VirtualMachine{
			Name:              "E48bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             48,
			Memory:            384,
			EmbodiedEmissions: 2.1983,
		},
		"E64bs v5": azure_models.VirtualMachine{
			Name:              "E64bs v5",
			Series:            "E2bs – E64bs v5",
			VCPUs:             64,
			Memory:            512,
			EmbodiedEmissions: 2.1983,
		},
		// NC A100 v4 series
		"NC24ads A100 v4": azure_models.VirtualMachine{
			Name:              "NC24ads A100 v4",
			Series:            "NC A100 v4 series",
			VCPUs:             24,
			Memory:            220,
			EmbodiedEmissions: 2.2483,
		},
		"NC48ads A100 v4": azure_models.VirtualMachine{
			Name:              "NC48ads A100 v4",
			Series:            "NC A100 v4 series",
			VCPUs:             48,
			Memory:            440,
			EmbodiedEmissions: 2.2483,
		},
		"NC96ads A100 v4": azure_models.VirtualMachine{
			Name:              "NC96ads A100 v4",
			Series:            "NC A100 v4 series",
			VCPUs:             96,
			Memory:            880,
			EmbodiedEmissions: 2.2483,
		},
	}
)
