name: Develop PR - build test

on:
  pull_request:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Saves us from having to redownload all modules
      - name: Go Mod cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      -
        name: Test
        run: |
          just test

      -
        name: Build
        run: |
          just build-local
